// Банк вопросов теста ПДД Испании. Вопрос — по-испански, как на экзамене DGT,
// плюс перевод: человек учит и правило, и формулировку, которую увидит в зале.
// t — тема: velocidad | senales | prioridad | alcohol | multas | seguridad | documentos
// ⚠️ Правила сверены на сентябрь 2026. Что менялось недавно и стоит перепроверять
// на dgt.es: городские 30 км/ч (с мая 2021) и маячок V-16 вместо треугольников
// (обязателен с 1 января 2026).
const PREGUNTAS = [

// ===== СКОРОСТЬ =====
{t:"velocidad", q:"En autopista o autovía, un turismo puede circular como máximo a:", q_ru:"По автомагистрали (autopista/autovía) легковой автомобиль может ехать максимум:", o:["120 km/h","130 km/h","110 km/h"], a:0},
{t:"velocidad", q:"En carretera convencional, la velocidad máxima para turismos es:", q_ru:"На обычной загородной дороге (carretera convencional) максимум для легковых:", o:["90 km/h","100 km/h","80 km/h"], a:0},
{t:"velocidad", q:"En una calle urbana de un solo carril por sentido, el límite general es:", q_ru:"На городской улице с одной полосой в каждую сторону общий лимит:", o:["30 km/h","50 km/h","40 km/h"], a:0},
{t:"velocidad", q:"En vías urbanas de dos o más carriles por sentido, el límite general es:", q_ru:"На городских дорогах с двумя и более полосами в одну сторону лимит:", o:["50 km/h","30 km/h","60 km/h"], a:0},
{t:"velocidad", q:"En calles de plataforma única (acera y calzada al mismo nivel), el límite es:", q_ru:"На улицах, где тротуар и проезжая часть на одном уровне, лимит:", o:["20 km/h","30 km/h","10 km/h"], a:0},
{t:"velocidad", q:"La velocidad mínima en autopista, salvo señalización, es:", q_ru:"Минимальная скорость на автомагистрали, если нет знака:", o:["60 km/h","40 km/h","80 km/h"], a:0},
{t:"velocidad", q:"En España, ¿la lluvia reduce automáticamente el límite de velocidad?", q_ru:"Снижает ли дождь в Испании лимит скорости автоматически?", o:["No, pero obliga a adecuar la velocidad","Sí, 20 km/h menos","Sí, como en Francia"], a:0},
{t:"velocidad", q:"Un turismo que arrastra un remolque ligero en autovía puede ir a:", q_ru:"Легковой с лёгким прицепом по автомагистрали может ехать:", o:["90 km/h","120 km/h","100 km/h"], a:0},
{t:"velocidad", q:"En una zona residencial señalizada, la velocidad máxima es:", q_ru:"В обозначенной жилой зоне максимальная скорость:", o:["20 km/h","30 km/h","10 km/h"], a:0},
{t:"velocidad", q:"Para adelantar en carretera convencional, ¿puede superarse el límite?", q_ru:"Можно ли при обгоне на обычной дороге превысить лимит?", o:["No, ese margen ya no existe","Sí, en 20 km/h","Sí, en 10 km/h"], a:0},
{t:"velocidad", q:"El límite para autobuses en autopista es:", q_ru:"Лимит для автобусов на автомагистрали:", o:["100 km/h","120 km/h","90 km/h"], a:0},
{t:"velocidad", q:"En un tramo con velocidad recomendada (cuadro azul), circular más rápido:", q_ru:"На участке с рекомендованной скоростью (синий квадрат) ехать быстрее:", o:["Se permite si es seguro y no se supera el límite","Está prohibido","Se multa siempre"], a:0},
{t:"velocidad", q:"Los radares de tramo miden:", q_ru:"Камеры «на участке» (radar de tramo) измеряют:", o:["La velocidad media entre dos puntos","La velocidad en un punto","Solo de noche"], a:0},
{t:"velocidad", q:"En vía urbana, superar el límite en más de 30 km/h supone:", q_ru:"В городе превышение более чем на 30 км/ч — это:", o:["Multa y pérdida de puntos","Solo aviso","Multa sin puntos"], a:0},
{t:"velocidad", q:"La velocidad debe reducirse obligatoriamente al aproximarse a:", q_ru:"Скорость обязательно снижают при приближении к:", o:["Un paso de peatones","Una gasolinera","Un semáforo en verde"], a:0},
{t:"velocidad", q:"Los ciclomotores tienen prohibido circular por:", q_ru:"Мопедам запрещено движение по:", o:["Autopistas y autovías","Carreteras convencionales","Vías urbanas"], a:0},

// ===== ЗНАКИ =====
{t:"senales", q:"Las señales triangulares con borde rojo son de:", q_ru:"Треугольные знаки с красной каймой — это знаки:", o:["Advertencia de peligro","Obligación","Prohibición"], a:0},
{t:"senales", q:"Las señales circulares azules indican:", q_ru:"Круглые синие знаки означают:", o:["Obligación","Prohibición","Peligro"], a:0},
{t:"senales", q:"Una señal circular con borde rojo indica normalmente:", q_ru:"Круглый знак с красной каймой обычно означает:", o:["Prohibición o restricción","Obligación","Información"], a:0},
{t:"senales", q:"La señal octogonal roja STOP obliga a:", q_ru:"Восьмиугольный красный STOP обязывает:", o:["Detenerse por completo antes de la línea","Reducir la velocidad","Ceder solo si viene alguien"], a:0},
{t:"senales", q:"El triángulo invertido «Ceda el paso» significa:", q_ru:"Перевёрнутый треугольник «Ceda el paso» означает:", o:["Ceder el paso, sin detenerse obligatoriamente","Detenerse siempre","Prioridad para ti"], a:0},
{t:"senales", q:"Una línea continua en el centro de la calzada:", q_ru:"Сплошная линия по центру проезжей части:", o:["No puede rebasarse ni pisarse","Puede rebasarse para adelantar","Solo orienta"], a:0},
{t:"senales", q:"Las señales cuadradas o rectangulares azules son de:", q_ru:"Квадратные и прямоугольные синие знаки — это:", o:["Indicación e información","Prohibición","Peligro"], a:0},
{t:"senales", q:"La señal de calzada con prioridad (rombo amarillo) indica:", q_ru:"Знак «дорога с приоритетом» (жёлтый ромб) означает:", o:["Tienes prioridad en las intersecciones del tramo","Debes ceder siempre","Fin de la vía"], a:0},
{t:"senales", q:"Una señal con fondo amarillo en obras significa:", q_ru:"Знак на жёлтом фоне в зоне работ означает:", o:["Prevalece sobre la señalización habitual","Es solo informativa","Puede ignorarse"], a:0},
{t:"senales", q:"La marca amarilla en zigzag junto al bordillo indica:", q_ru:"Жёлтая зигзагообразная разметка у бордюра означает:", o:["Prohibido estacionar (parada o reserva)","Zona de carga","Aparcamiento libre"], a:0},
{t:"senales", q:"En caso de contradicción, ¿qué prevalece?", q_ru:"Если указания противоречат друг другу, что главнее?", o:["Las indicaciones del agente de tráfico","Las señales verticales","Las marcas viales"], a:0},
{t:"senales", q:"Una señal circular blanca con borde rojo y nada dentro significa:", q_ru:"Круглый белый знак с красной каймой и пустой внутри означает:", o:["Circulación prohibida en ambos sentidos","Fin de prohibiciones","Dirección obligatoria"], a:0},
{t:"senales", q:"El panel con una flecha blanca sobre fondo azul indica:", q_ru:"Синий знак с белой стрелкой означает:", o:["Sentido obligatorio","Sentido prohibido","Vía de servicio"], a:0},
{t:"senales", q:"Las señales de fin de prohibición suelen ser:", q_ru:"Знаки отмены запрета обычно:", o:["Circulares con banda oblicua","Triangulares","Cuadradas azules"], a:0},
{t:"senales", q:"Una línea longitudinal discontinua permite:", q_ru:"Прерывистая продольная линия разрешает:", o:["Rebasarla para adelantar o cambiar de carril","Solo adelantar a ciclistas","Nada, es decorativa"], a:0},
{t:"senales", q:"El semáforo ámbar fijo obliga a:", q_ru:"Постоянный жёлтый сигнал светофора обязывает:", o:["Detenerse, salvo que frenar sea peligroso","Acelerar","Seguir siempre"], a:0},

// ===== ПРИОРИТЕТ =====
{t:"prioridad", q:"En una glorieta (rotonda), la prioridad la tienen:", q_ru:"На круговом (glorieta) приоритет у:", o:["Los vehículos que ya circulan por ella","Los que entran","Los que van más rápido"], a:0},
{t:"prioridad", q:"En un cruce sin señales ni semáforos, la prioridad es:", q_ru:"На перекрёстке без знаков и светофоров приоритет:", o:["Del que viene por la derecha","Del que va recto","Del más pesado"], a:0},
{t:"prioridad", q:"Al salir de un aparcamiento o vía privada:", q_ru:"При выезде с парковки или частной территории:", o:["Debes ceder el paso a todos","Tienes prioridad","Solo cedes a los peatones"], a:0},
{t:"prioridad", q:"Un vehículo de emergencia con señales luminosas y acústicas:", q_ru:"Спецтранспорт с включёнными маячком и сиреной:", o:["Tiene prioridad y hay que facilitarle el paso","Solo en ciudad","No tiene prioridad en glorietas"], a:0},
{t:"prioridad", q:"En un paso de peatones sin semáforo, el peatón:", q_ru:"На пешеходном переходе без светофора пешеход:", o:["Tiene prioridad","Debe esperar al coche","Solo tiene prioridad de día"], a:0},
{t:"prioridad", q:"En una calle estrecha donde no caben dos vehículos:", q_ru:"На узкой улице, где двоим не разъехаться:", o:["Cede el que tenga la maniobra más fácil, según señalización","Cede siempre el que baja","Cede siempre el más pequeño"], a:0},
{t:"prioridad", q:"Los tranvías y vehículos sobre raíles:", q_ru:"Трамваи и рельсовый транспорт:", o:["Tienen prioridad sobre el resto","Ceden en glorietas","No tienen prioridad"], a:0},
{t:"prioridad", q:"Al girar a la derecha y cruzar un carril bici:", q_ru:"Поворачивая направо через велополосу:", o:["Debes ceder el paso a los ciclistas","Tienes prioridad","Tocas el claxon"], a:0},
{t:"prioridad", q:"Al hacer un cambio de sentido, cedes el paso a:", q_ru:"При развороте уступаешь:", o:["Todos los vehículos, vengan de donde vengan","Solo a los de la izquierda","A nadie si hay hueco"], a:0},
{t:"prioridad", q:"Un autobús urbano que sale de su parada señalizada:", q_ru:"Городской автобус, отъезжающий от обозначенной остановки:", o:["Tiene prioridad en vía urbana","No tiene prioridad","Solo de día"], a:0},
{t:"prioridad", q:"En una intersección regulada por agente, sus señales:", q_ru:"На перекрёстке с регулировщиком его сигналы:", o:["Prevalecen sobre semáforos y señales","Valen menos que el semáforo","Son consejos"], a:0},
{t:"prioridad", q:"Al incorporarte a una autovía por el carril de aceleración:", q_ru:"При выезде на автомагистраль по полосе разгона:", o:["Debes ceder el paso a los que ya circulan","Tienes prioridad","Frenas al final del carril"], a:0},
{t:"prioridad", q:"Un ciclista dentro de una glorieta:", q_ru:"Велосипедист внутри кругового:", o:["Tiene prioridad como cualquier vehículo dentro","Debe ceder siempre","No puede entrar"], a:0},
{t:"prioridad", q:"Los peatones en una zona peatonal o residencial:", q_ru:"Пешеходы в пешеходной или жилой зоне:", o:["Tienen prioridad sobre los vehículos","Ceden a los coches","Solo pueden cruzar por pasos"], a:0},
{t:"prioridad", q:"Si un semáforo está apagado o en ámbar intermitente, rige:", q_ru:"Если светофор погас или мигает жёлтым, действуют:", o:["La señalización vertical o la prioridad de la derecha","Nada, pasa el primero","Siempre el que viene de frente"], a:0},

// ===== АЛКОГОЛЬ И НАРКОТИКИ =====
{t:"alcohol", q:"La tasa general máxima de alcohol en aire espirado es:", q_ru:"Общий максимум алкоголя в выдыхаемом воздухе:", o:["0,25 mg/l","0,30 mg/l","0,15 mg/l"], a:0},
{t:"alcohol", q:"La tasa general máxima de alcohol en sangre es:", q_ru:"Общий максимум алкоголя в крови:", o:["0,5 g/l","0,8 g/l","0,3 g/l"], a:0},
{t:"alcohol", q:"Para conductores noveles y profesionales, la tasa en aire es:", q_ru:"Для новичков и профессионалов норма в выдыхаемом воздухе:", o:["0,15 mg/l","0,25 mg/l","0,30 mg/l"], a:0},
{t:"alcohol", q:"La presencia de drogas en el organismo del conductor:", q_ru:"Наличие наркотиков в организме водителя:", o:["Está prohibida, con tolerancia cero","Se tolera en pequeña cantidad","Solo se sanciona si hay accidente"], a:0},
{t:"alcohol", q:"Negarse a las pruebas de alcoholemia es:", q_ru:"Отказ от проверки на алкоголь — это:", o:["Delito penal","Falta leve","Algo sin consecuencias"], a:0},
{t:"alcohol", q:"Conducir con 0,60 mg/l en aire espirado es:", q_ru:"Управление с показателем 0,60 мг/л в воздухе — это:", o:["Delito contra la seguridad vial","Infracción leve","Infracción administrativa sin más"], a:0},
{t:"alcohol", q:"El alcohol, sobre el conductor, produce:", q_ru:"Алкоголь на водителя действует так:", o:["Aumenta el tiempo de reacción y da falsa seguridad","Mejora los reflejos","Solo afecta a la vista"], a:0},
{t:"alcohol", q:"El café o una ducha fría tras beber:", q_ru:"Кофе или холодный душ после выпитого:", o:["No reducen la tasa de alcohol","La reducen a la mitad","La eliminan"], a:0},
{t:"alcohol", q:"Los medicamentos que producen somnolencia se señalan con:", q_ru:"Лекарства, вызывающие сонливость, помечают:", o:["Un pictograma de conducción en la caja","Nada especial","Una etiqueta verde"], a:0},
{t:"alcohol", q:"El control de alcoholemia puede hacerse:", q_ru:"Проверку на алкоголь могут провести:", o:["En cualquier control preventivo, sin infracción previa","Solo tras un accidente","Solo si hay denuncia"], a:0},
{t:"alcohol", q:"Superar la tasa permitida de alcohol resta:", q_ru:"Превышение допустимой нормы алкоголя отнимает:", o:["4 o 6 puntos según la tasa","1 punto","Ningún punto"], a:0},
{t:"alcohol", q:"La eliminación del alcohol en el cuerpo depende sobre todo de:", q_ru:"Вывод алкоголя из организма зависит прежде всего от:", o:["El tiempo","La comida","El ejercicio"], a:0},
{t:"alcohol", q:"Dar positivo en drogas al volante supone:", q_ru:"Положительный тест на наркотики за рулём означает:", o:["Multa elevada y pérdida de puntos","Solo advertencia","Multa de 200 €"], a:0},
{t:"alcohol", q:"Tras una noche de fiesta, por la mañana:", q_ru:"После ночной вечеринки утром:", o:["Aún puede haber alcohol en sangre","El cuerpo siempre está limpio","Basta con dormir dos horas"], a:0},

// ===== ШТРАФЫ И БАЛЛЫ =====
{t:"multas", q:"Un conductor con permiso ordinario dispone inicialmente de:", q_ru:"У обычного водителя изначально баллов:", o:["12 puntos","15 puntos","8 puntos"], a:0},
{t:"multas", q:"Un conductor novel dispone de:", q_ru:"У начинающего водителя баллов:", o:["8 puntos","12 puntos","6 puntos"], a:0},
{t:"multas", q:"Tras tres años sin perder puntos, el saldo puede llegar a:", q_ru:"После трёх лет без потерь баланс может вырасти до:", o:["15 puntos","12 puntos","20 puntos"], a:0},
{t:"multas", q:"Usar el teléfono móvil en la mano conduciendo resta:", q_ru:"Телефон в руке за рулём отнимает:", o:["6 puntos","3 puntos","1 punto"], a:0},
{t:"multas", q:"No usar el cinturón de seguridad resta:", q_ru:"Непристёгнутый ремень отнимает:", o:["4 puntos","2 puntos","6 puntos"], a:0},
{t:"multas", q:"Una multa pagada en los 20 días naturales tiene descuento del:", q_ru:"Штраф при оплате в течение 20 дней даёт скидку:", o:["50 %","30 %","20 %"], a:0},
{t:"multas", q:"Al quedarse sin puntos, el conductor:", q_ru:"Оставшись без баллов, водитель:", o:["Pierde la vigencia del permiso y debe recuperarlo con cursos","Paga una multa y sigue","Espera un año sin más"], a:0},
{t:"multas", q:"Las multas pueden notificarse electrónicamente a través de:", q_ru:"Штрафы могут приходить электронно через:", o:["La Dirección Electrónica Vial (DEV)","Un SMS obligatorio","Solo correo certificado"], a:0},
{t:"multas", q:"Conducir sin seguro obligatorio supone:", q_ru:"Езда без обязательной страховки — это:", o:["Multa elevada e inmovilización del vehículo","Advertencia","Multa de 80 €"], a:0},
{t:"multas", q:"Arrojar a la vía objetos que puedan provocar incendio resta:", q_ru:"Выброс на дорогу предметов, способных вызвать пожар, отнимает:", o:["6 puntos","4 puntos","2 puntos"], a:0},
{t:"multas", q:"El plazo general para recurrir una multa es de:", q_ru:"Общий срок обжалования штрафа:", o:["20 días naturales","10 días","3 meses"], a:0},
{t:"multas", q:"Circular por el arcén sin causa justificada es:", q_ru:"Езда по обочине без причины — это:", o:["Infracción sancionable","Permitido si hay atasco","Permitido de día"], a:0},
{t:"multas", q:"No respetar un semáforo en rojo resta:", q_ru:"Проезд на красный отнимает:", o:["4 puntos","2 puntos","6 puntos"], a:0},
{t:"multas", q:"Para recuperar el saldo total de puntos hay que:", q_ru:"Чтобы вернуть полный баланс баллов, нужно:", o:["Pasar dos años sin infracciones graves","Pagar una tasa","Esperar seis meses"], a:0},

// ===== БЕЗОПАСНОСТЬ И ТЕХНИКА =====
{t:"seguridad", q:"Desde el 1 de enero de 2026, en caso de avería hay que señalizar con:", q_ru:"С 1 января 2026 года при поломке обозначаться нужно:", o:["La baliza luminosa V-16 conectada","Dos triángulos","Un triángulo y el chaleco"], a:0},
{t:"seguridad", q:"La baliza V-16 se coloca:", q_ru:"Маячок V-16 ставится:", o:["En el punto más alto del vehículo, sin bajar a la calzada","A 50 m por detrás","Dentro del coche"], a:0},
{t:"seguridad", q:"El chaleco reflectante debe ponerse:", q_ru:"Светоотражающий жилет надевают:", o:["Antes de salir del vehículo a la calzada","Solo de noche","Solo en autopista"], a:0},
{t:"seguridad", q:"Los niños de menos de 135 cm deben viajar:", q_ru:"Дети ростом менее 135 см должны ехать:", o:["En los asientos traseros con sistema de retención","Delante con cinturón","Donde quieran"], a:0},
{t:"seguridad", q:"La ITV de un turismo particular de 4 a 10 años se pasa:", q_ru:"Техосмотр (ITV) легкового 4-10 лет проходят:", o:["Cada dos años","Cada año","Cada cuatro años"], a:0},
{t:"seguridad", q:"La profundidad mínima legal del dibujo de los neumáticos es:", q_ru:"Минимальная законная глубина протектора шин:", o:["1,6 mm","2,5 mm","1,0 mm"], a:0},
{t:"seguridad", q:"El casco es obligatorio para motoristas:", q_ru:"Шлем для мотоциклистов обязателен:", o:["Siempre, también en ciudad","Solo fuera de ciudad","Solo en autovía"], a:0},
{t:"seguridad", q:"Con niebla densa deben encenderse:", q_ru:"В густом тумане включают:", o:["Las luces de niebla y la de cruce","Las largas","Solo las de posición"], a:0},
{t:"seguridad", q:"Las luces de carretera (largas) deben apagarse:", q_ru:"Дальний свет выключают:", o:["Al cruzarse con otro vehículo o seguirlo de cerca","Nunca","Solo en ciudad"], a:0},
{t:"seguridad", q:"La distancia de seguridad debe permitir:", q_ru:"Дистанция безопасности должна позволять:", o:["Detenerse sin colisionar ante una frenada brusca","Adelantar rápido","Ver la matrícula"], a:0},
{t:"seguridad", q:"El cinturón de seguridad es obligatorio:", q_ru:"Ремень безопасности обязателен:", o:["En todas las plazas, delante y detrás","Solo delante","Solo fuera de ciudad"], a:0},
{t:"seguridad", q:"El aquaplaning se produce cuando:", q_ru:"Аквапланирование возникает, когда:", o:["Una capa de agua separa el neumático del asfalto","Se calienta el motor","Frenas en seco"], a:0},
{t:"seguridad", q:"Ante un reventón de neumático en marcha hay que:", q_ru:"При разрыве шины на ходу нужно:", o:["Sujetar firme el volante y frenar suave","Frenar a fondo","Girar rápido al arcén"], a:0},
{t:"seguridad", q:"La presión de los neumáticos se comprueba:", q_ru:"Давление в шинах проверяют:", o:["En frío y al menos una vez al mes","En caliente","Una vez al año"], a:0},
{t:"seguridad", q:"Hablar por teléfono con cascos o auriculares conduciendo:", q_ru:"Разговор по телефону в наушниках за рулём:", o:["Está prohibido","Está permitido","Se permite en ciudad"], a:0},
{t:"seguridad", q:"La somnolencia al volante se combate:", q_ru:"С сонливостью за рулём борются:", o:["Parando a descansar","Subiendo la música","Abriendo la ventanilla y siguiendo"], a:0},

// ===== ДОКУМЕНТЫ И ЭКЗАМЕН =====
{t:"documentos", q:"El examen teórico de la DGT consta de:", q_ru:"Теоретический экзамен DGT состоит из:", o:["30 preguntas, con 3 fallos como máximo","40 preguntas, 5 fallos","20 preguntas, 2 fallos"], a:0},
{t:"documentos", q:"El organismo que gestiona permisos y exámenes en España es:", q_ru:"Права и экзамены в Испании ведёт:", o:["La DGT (Dirección General de Tráfico)","El ayuntamiento","La Seguridad Social"], a:0},
{t:"documentos", q:"El expediente del permiso se lleva en:", q_ru:"Личное дело по правам ведёт:", o:["La Jefatura Provincial de Tráfico","La comisaría","La embajada"], a:0},
{t:"documentos", q:"El canje de un permiso extranjero es posible:", q_ru:"Обмен иностранных прав (canje) возможен:", o:["Solo con países que tienen acuerdo con España","Con cualquier país","Solo con la UE"], a:0},
{t:"documentos", q:"Documentación obligatoria del vehículo:", q_ru:"Обязательные документы на автомобиль:", o:["Permiso de circulación, ficha técnica y seguro","Solo el seguro","Solo la ficha técnica"], a:0},
{t:"documentos", q:"El permiso B permite conducir turismos con masa máxima de hasta:", q_ru:"Категория B разрешает автомобили с максимальной массой до:", o:["3.500 kg","5.000 kg","2.500 kg"], a:0},
{t:"documentos", q:"El permiso B se obtiene a partir de los:", q_ru:"Категорию B можно получить с:", o:["18 años","16 años","21 años"], a:0},
{t:"documentos", q:"Tras aprobar el teórico, el práctico debe hacerse dentro de:", q_ru:"После сдачи теории практику нужно сдать в течение:", o:["Dos años de validez del teórico","Seis meses","Un mes"], a:0},
{t:"documentos", q:"La L de conductor novel debe llevarse:", q_ru:"Знак L (новичок) нужно возить:", o:["El primer año, visible en la parte trasera","Tres años","No es obligatoria"], a:0},
{t:"documentos", q:"¿Tiene el conductor novel un límite de velocidad especial?", q_ru:"Есть ли у начинающего водителя особый лимит скорости?", o:["No, ese límite ya no existe","Sí, 80 km/h","Sí, 100 km/h"], a:0},
{t:"documentos", q:"La renovación del permiso B para menores de 65 años es cada:", q_ru:"Продление категории B для тех, кому меньше 65, — каждые:", o:["10 años","5 años","15 años"], a:0},
{t:"documentos", q:"Para renovar el permiso hace falta:", q_ru:"Для продления прав нужно:", o:["Un informe de aptitud psicofísica de un centro autorizado","Solo pagar la tasa","Un examen teórico"], a:0},
{t:"documentos", q:"Conducir sin haber obtenido nunca el permiso es:", q_ru:"Езда без когда-либо полученных прав — это:", o:["Delito penal","Infracción leve","Multa de 200 €"], a:0},
{t:"documentos", q:"El permiso de conducir debe llevarse:", q_ru:"Права нужно возить:", o:["Siempre encima al conducir","Solo en viajes largos","Basta una foto en el móvil"], a:0},
];
if (typeof module !== "undefined") module.exports = PREGUNTAS;
