/* Вопросы, собранные из таблиц правил: `python generar-preguntas.py`.

   ⚠️ РУКАМИ НЕ ПРАВИТЬ — перезапишется при следующей сборке. Правило живёт
   в таблице внутри generar-preguntas.py; ошиблись в правиле — поправили в одном
   месте, и оно разъехалось по всем вопросам разом.

   Рукописные вопросы (на понимание, на ситуацию) лежат отдельно, в preguntas.js,
   и генератор их не трогает. Оба банка складываются в браузере. */

const PREGUNTAS_AUTO = [
{t:"velocidad", q:"En autopista o autovía, un autobús puede circular como máximo a:", q_ru:"По автомагистрали автобусу разрешено максимум:",
 o:["100 km/h","110 km/h","130 km/h"], o_ru:["100 км/ч","110 км/ч","130 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 100 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un autobús en autopista o autovía?", q_ru:"Какова максимальная скорость автобусу по автомагистрали?",
 o:["100 km/h","120 km/h","60 km/h"], o_ru:["100 км/ч","120 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 100 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un autobús en autopista o autovía es de:", q_ru:"Ограничение скорости автобусу по автомагистрали составляет:",
 o:["100 km/h","60 km/h","120 km/h"], o_ru:["100 км/ч","60 км/ч","120 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 100 км/ч."},
{t:"velocidad", q:"En autopista o autovía, un camión de más de 3.500 kg puede circular como máximo a:", q_ru:"По автомагистрали грузовику тяжелее 3500 кг разрешено максимум:",
 o:["90 km/h","70 km/h","60 km/h"], o_ru:["90 км/ч","70 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 90 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un camión de más de 3.500 kg en autopista o autovía?", q_ru:"Какова максимальная скорость грузовику тяжелее 3500 кг по автомагистрали?",
 o:["90 km/h","130 km/h","110 km/h"], o_ru:["90 км/ч","130 км/ч","110 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 90 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un camión de más de 3.500 kg en autopista o autovía es de:", q_ru:"Ограничение скорости грузовику тяжелее 3500 кг по автомагистрали составляет:",
 o:["90 km/h","130 km/h","60 km/h"], o_ru:["90 км/ч","130 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 90 км/ч."},
{t:"velocidad", q:"En autopista o autovía, una motocicleta puede circular como máximo a:", q_ru:"По автомагистрали мотоциклу разрешено максимум:",
 o:["120 km/h","130 km/h","80 km/h"], o_ru:["120 км/ч","130 км/ч","80 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 120 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de una motocicleta en autopista o autovía?", q_ru:"Какова максимальная скорость мотоциклу по автомагистрали?",
 o:["120 km/h","90 km/h","80 km/h"], o_ru:["120 км/ч","90 км/ч","80 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 120 км/ч."},
{t:"velocidad", q:"El límite de velocidad de una motocicleta en autopista o autovía es de:", q_ru:"Ограничение скорости мотоциклу по автомагистрали составляет:",
 o:["120 km/h","90 km/h","100 km/h"], o_ru:["120 км/ч","90 км/ч","100 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 120 км/ч."},
{t:"velocidad", q:"En autopista o autovía, un turismo con remolque ligero puede circular como máximo a:", q_ru:"По автомагистрали легковому с лёгким прицепом разрешено максимум:",
 o:["90 km/h","120 km/h","110 km/h"], o_ru:["90 км/ч","120 км/ч","110 км/ч"], a:0,
 e:"По таблице лимитов: Легковому с лёгким прицепом — 90 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo con remolque ligero en autopista o autovía?", q_ru:"Какова максимальная скорость легковому с лёгким прицепом по автомагистрали?",
 o:["90 km/h","120 km/h","100 km/h"], o_ru:["90 км/ч","120 км/ч","100 км/ч"], a:0,
 e:"По таблице лимитов: Легковому с лёгким прицепом — 90 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo con remolque ligero en autopista o autovía es de:", q_ru:"Ограничение скорости легковому с лёгким прицепом по автомагистрали составляет:",
 o:["90 km/h","120 km/h","110 km/h"], o_ru:["90 км/ч","120 км/ч","110 км/ч"], a:0,
 e:"По таблице лимитов: Легковому с лёгким прицепом — 90 км/ч."},
{t:"velocidad", q:"En autopista o autovía, un turismo puede circular como máximo a:", q_ru:"По автомагистрали легковому автомобилю разрешено максимум:",
 o:["120 km/h","80 km/h","100 km/h"], o_ru:["120 км/ч","80 км/ч","100 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 120 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo en autopista o autovía?", q_ru:"Какова максимальная скорость легковому автомобилю по автомагистрали?",
 o:["120 km/h","80 km/h","100 km/h"], o_ru:["120 км/ч","80 км/ч","100 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 120 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo en autopista o autovía es de:", q_ru:"Ограничение скорости легковому автомобилю по автомагистрали составляет:",
 o:["120 km/h","130 km/h","110 km/h"], o_ru:["120 км/ч","130 км/ч","110 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 120 км/ч."},
{t:"velocidad", q:"En carretera convencional, un autobús puede circular como máximo a:", q_ru:"По обычной загородной дороге автобусу разрешено максимум:",
 o:["90 km/h","70 km/h","120 km/h"], o_ru:["90 км/ч","70 км/ч","120 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 90 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un autobús en carretera convencional?", q_ru:"Какова максимальная скорость автобусу по обычной загородной дороге?",
 o:["90 km/h","70 km/h","120 km/h"], o_ru:["90 км/ч","70 км/ч","120 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 90 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un autobús en carretera convencional es de:", q_ru:"Ограничение скорости автобусу по обычной загородной дороге составляет:",
 o:["90 km/h","100 km/h","60 km/h"], o_ru:["90 км/ч","100 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 90 км/ч."},
{t:"velocidad", q:"En carretera convencional, un camión de más de 3.500 kg puede circular como máximo a:", q_ru:"По обычной загородной дороге грузовику тяжелее 3500 кг разрешено максимум:",
 o:["80 km/h","100 km/h","60 km/h"], o_ru:["80 км/ч","100 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 80 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un camión de más de 3.500 kg en carretera convencional?", q_ru:"Какова максимальная скорость грузовику тяжелее 3500 кг по обычной загородной дороге?",
 o:["80 km/h","50 km/h","60 km/h"], o_ru:["80 км/ч","50 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 80 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un camión de más de 3.500 kg en carretera convencional es de:", q_ru:"Ограничение скорости грузовику тяжелее 3500 кг по обычной загородной дороге составляет:",
 o:["80 km/h","60 km/h","120 km/h"], o_ru:["80 км/ч","60 км/ч","120 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 80 км/ч."},
{t:"velocidad", q:"En carretera convencional, una motocicleta puede circular como máximo a:", q_ru:"По обычной загородной дороге мотоциклу разрешено максимум:",
 o:["90 km/h","100 km/h","70 km/h"], o_ru:["90 км/ч","100 км/ч","70 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 90 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de una motocicleta en carretera convencional?", q_ru:"Какова максимальная скорость мотоциклу по обычной загородной дороге?",
 o:["90 km/h","70 km/h","120 km/h"], o_ru:["90 км/ч","70 км/ч","120 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 90 км/ч."},
{t:"velocidad", q:"El límite de velocidad de una motocicleta en carretera convencional es de:", q_ru:"Ограничение скорости мотоциклу по обычной загородной дороге составляет:",
 o:["90 km/h","130 km/h","80 km/h"], o_ru:["90 км/ч","130 км/ч","80 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 90 км/ч."},
{t:"velocidad", q:"En carretera convencional, un turismo con remolque ligero puede circular como máximo a:", q_ru:"По обычной загородной дороге легковому с лёгким прицепом разрешено максимум:",
 o:["70 km/h","30 km/h","50 km/h"], o_ru:["70 км/ч","30 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Легковому с лёгким прицепом — 70 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo con remolque ligero en carretera convencional?", q_ru:"Какова максимальная скорость легковому с лёгким прицепом по обычной загородной дороге?",
 o:["70 km/h","80 km/h","50 km/h"], o_ru:["70 км/ч","80 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Легковому с лёгким прицепом — 70 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo con remolque ligero en carretera convencional es de:", q_ru:"Ограничение скорости легковому с лёгким прицепом по обычной загородной дороге составляет:",
 o:["70 km/h","100 km/h","110 km/h"], o_ru:["70 км/ч","100 км/ч","110 км/ч"], a:0,
 e:"По таблице лимитов: Легковому с лёгким прицепом — 70 км/ч."},
{t:"velocidad", q:"En carretera convencional, un turismo puede circular como máximo a:", q_ru:"По обычной загородной дороге легковому автомобилю разрешено максимум:",
 o:["90 km/h","120 km/h","110 km/h"], o_ru:["90 км/ч","120 км/ч","110 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 90 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo en carretera convencional?", q_ru:"Какова максимальная скорость легковому автомобилю по обычной загородной дороге?",
 o:["90 km/h","120 km/h","70 km/h"], o_ru:["90 км/ч","120 км/ч","70 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 90 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo en carretera convencional es de:", q_ru:"Ограничение скорости легковому автомобилю по обычной загородной дороге составляет:",
 o:["90 km/h","60 km/h","70 km/h"], o_ru:["90 км/ч","60 км/ч","70 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 90 км/ч."},
{t:"velocidad", q:"En calle de plataforma única, una motocicleta puede circular como máximo a:", q_ru:"По улице с единым уровнем тротуара и проезжей части мотоциклу разрешено максимум:",
 o:["20 km/h","50 km/h","60 km/h"], o_ru:["20 км/ч","50 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 20 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de una motocicleta en calle de plataforma única?", q_ru:"Какова максимальная скорость мотоциклу по улице с единым уровнем тротуара и проезжей части?",
 o:["20 km/h","30 km/h","40 km/h"], o_ru:["20 км/ч","30 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 20 км/ч."},
{t:"velocidad", q:"El límite de velocidad de una motocicleta en calle de plataforma única es de:", q_ru:"Ограничение скорости мотоциклу по улице с единым уровнем тротуара и проезжей части составляет:",
 o:["20 km/h","30 km/h","60 km/h"], o_ru:["20 км/ч","30 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 20 км/ч."},
{t:"velocidad", q:"En calle de plataforma única, un turismo puede circular como máximo a:", q_ru:"По улице с единым уровнем тротуара и проезжей части легковому автомобилю разрешено максимум:",
 o:["20 km/h","30 km/h","40 km/h"], o_ru:["20 км/ч","30 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 20 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo en calle de plataforma única?", q_ru:"Какова максимальная скорость легковому автомобилю по улице с единым уровнем тротуара и проезжей части?",
 o:["20 km/h","40 km/h","60 km/h"], o_ru:["20 км/ч","40 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 20 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo en calle de plataforma única es de:", q_ru:"Ограничение скорости легковому автомобилю по улице с единым уровнем тротуара и проезжей части составляет:",
 o:["20 km/h","60 km/h","40 km/h"], o_ru:["20 км/ч","60 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 20 км/ч."},
{t:"velocidad", q:"En zona residencial, una motocicleta puede circular como máximo a:", q_ru:"По жилой зоне мотоциклу разрешено максимум:",
 o:["20 km/h","40 km/h","30 km/h"], o_ru:["20 км/ч","40 км/ч","30 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 20 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de una motocicleta en zona residencial?", q_ru:"Какова максимальная скорость мотоциклу по жилой зоне?",
 o:["20 km/h","30 km/h","60 km/h"], o_ru:["20 км/ч","30 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 20 км/ч."},
{t:"velocidad", q:"El límite de velocidad de una motocicleta en zona residencial es de:", q_ru:"Ограничение скорости мотоциклу по жилой зоне составляет:",
 o:["20 km/h","60 km/h","40 km/h"], o_ru:["20 км/ч","60 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 20 км/ч."},
{t:"velocidad", q:"En zona residencial, un turismo puede circular como máximo a:", q_ru:"По жилой зоне легковому автомобилю разрешено максимум:",
 o:["20 km/h","40 km/h","50 km/h"], o_ru:["20 км/ч","40 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 20 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo en zona residencial?", q_ru:"Какова максимальная скорость легковому автомобилю по жилой зоне?",
 o:["20 km/h","40 km/h","50 km/h"], o_ru:["20 км/ч","40 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 20 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo en zona residencial es de:", q_ru:"Ограничение скорости легковому автомобилю по жилой зоне составляет:",
 o:["20 km/h","30 km/h","40 km/h"], o_ru:["20 км/ч","30 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 20 км/ч."},
{t:"velocidad", q:"En vía urbana de un carril por sentido, un autobús puede circular como máximo a:", q_ru:"По городской улице с одной полосой в каждую сторону автобусу разрешено максимум:",
 o:["30 km/h","50 km/h","20 km/h"], o_ru:["30 км/ч","50 км/ч","20 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 30 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un autobús en vía urbana de un carril por sentido?", q_ru:"Какова максимальная скорость автобусу по городской улице с одной полосой в каждую сторону?",
 o:["30 km/h","40 km/h","50 km/h"], o_ru:["30 км/ч","40 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 30 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un autobús en vía urbana de un carril por sentido es de:", q_ru:"Ограничение скорости автобусу по городской улице с одной полосой в каждую сторону составляет:",
 o:["30 km/h","20 km/h","60 km/h"], o_ru:["30 км/ч","20 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 30 км/ч."},
{t:"velocidad", q:"En vía urbana de un carril por sentido, un camión de más de 3.500 kg puede circular como máximo a:", q_ru:"По городской улице с одной полосой в каждую сторону грузовику тяжелее 3500 кг разрешено максимум:",
 o:["30 km/h","40 km/h","50 km/h"], o_ru:["30 км/ч","40 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 30 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un camión de más de 3.500 kg en vía urbana de un carril por sentido?", q_ru:"Какова максимальная скорость грузовику тяжелее 3500 кг по городской улице с одной полосой в каждую сторону?",
 o:["30 km/h","40 km/h","50 km/h"], o_ru:["30 км/ч","40 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 30 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un camión de más de 3.500 kg en vía urbana de un carril por sentido es de:", q_ru:"Ограничение скорости грузовику тяжелее 3500 кг по городской улице с одной полосой в каждую сторону составляет:",
 o:["30 km/h","20 km/h","50 km/h"], o_ru:["30 км/ч","20 км/ч","50 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 30 км/ч."},
{t:"velocidad", q:"En vía urbana de un carril por sentido, una motocicleta puede circular como máximo a:", q_ru:"По городской улице с одной полосой в каждую сторону мотоциклу разрешено максимум:",
 o:["30 km/h","50 km/h","70 km/h"], o_ru:["30 км/ч","50 км/ч","70 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 30 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de una motocicleta en vía urbana de un carril por sentido?", q_ru:"Какова максимальная скорость мотоциклу по городской улице с одной полосой в каждую сторону?",
 o:["30 km/h","70 km/h","60 km/h"], o_ru:["30 км/ч","70 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 30 км/ч."},
{t:"velocidad", q:"El límite de velocidad de una motocicleta en vía urbana de un carril por sentido es de:", q_ru:"Ограничение скорости мотоциклу по городской улице с одной полосой в каждую сторону составляет:",
 o:["30 km/h","50 km/h","40 km/h"], o_ru:["30 км/ч","50 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 30 км/ч."},
{t:"velocidad", q:"En vía urbana de un carril por sentido, un turismo puede circular como máximo a:", q_ru:"По городской улице с одной полосой в каждую сторону легковому автомобилю разрешено максимум:",
 o:["30 km/h","70 km/h","60 km/h"], o_ru:["30 км/ч","70 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 30 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo en vía urbana de un carril por sentido?", q_ru:"Какова максимальная скорость легковому автомобилю по городской улице с одной полосой в каждую сторону?",
 o:["30 km/h","60 km/h","40 km/h"], o_ru:["30 км/ч","60 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 30 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo en vía urbana de un carril por sentido es de:", q_ru:"Ограничение скорости легковому автомобилю по городской улице с одной полосой в каждую сторону составляет:",
 o:["30 km/h","40 km/h","60 km/h"], o_ru:["30 км/ч","40 км/ч","60 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 30 км/ч."},
{t:"velocidad", q:"En vía urbana de dos carriles por sentido, un autobús puede circular como máximo a:", q_ru:"По городской дороге с двумя полосами в одну сторону автобусу разрешено максимум:",
 o:["50 km/h","80 km/h","90 km/h"], o_ru:["50 км/ч","80 км/ч","90 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 50 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un autobús en vía urbana de dos carriles por sentido?", q_ru:"Какова максимальная скорость автобусу по городской дороге с двумя полосами в одну сторону?",
 o:["50 km/h","70 km/h","40 km/h"], o_ru:["50 км/ч","70 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 50 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un autobús en vía urbana de dos carriles por sentido es de:", q_ru:"Ограничение скорости автобусу по городской дороге с двумя полосами в одну сторону составляет:",
 o:["50 km/h","20 km/h","90 km/h"], o_ru:["50 км/ч","20 км/ч","90 км/ч"], a:0,
 e:"По таблице лимитов: Автобусу — 50 км/ч."},
{t:"velocidad", q:"En vía urbana de dos carriles por sentido, un camión de más de 3.500 kg puede circular como máximo a:", q_ru:"По городской дороге с двумя полосами в одну сторону грузовику тяжелее 3500 кг разрешено максимум:",
 o:["50 km/h","70 km/h","90 km/h"], o_ru:["50 км/ч","70 км/ч","90 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 50 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un camión de más de 3.500 kg en vía urbana de dos carriles por sentido?", q_ru:"Какова максимальная скорость грузовику тяжелее 3500 кг по городской дороге с двумя полосами в одну сторону?",
 o:["50 km/h","60 km/h","40 km/h"], o_ru:["50 км/ч","60 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 50 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un camión de más de 3.500 kg en vía urbana de dos carriles por sentido es de:", q_ru:"Ограничение скорости грузовику тяжелее 3500 кг по городской дороге с двумя полосами в одну сторону составляет:",
 o:["50 km/h","60 km/h","90 km/h"], o_ru:["50 км/ч","60 км/ч","90 км/ч"], a:0,
 e:"По таблице лимитов: Грузовику тяжелее 3500 кг — 50 км/ч."},
{t:"velocidad", q:"En vía urbana de dos carriles por sentido, una motocicleta puede circular como máximo a:", q_ru:"По городской дороге с двумя полосами в одну сторону мотоциклу разрешено максимум:",
 o:["50 km/h","70 km/h","20 km/h"], o_ru:["50 км/ч","70 км/ч","20 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 50 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de una motocicleta en vía urbana de dos carriles por sentido?", q_ru:"Какова максимальная скорость мотоциклу по городской дороге с двумя полосами в одну сторону?",
 o:["50 km/h","60 km/h","80 km/h"], o_ru:["50 км/ч","60 км/ч","80 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 50 км/ч."},
{t:"velocidad", q:"El límite de velocidad de una motocicleta en vía urbana de dos carriles por sentido es de:", q_ru:"Ограничение скорости мотоциклу по городской дороге с двумя полосами в одну сторону составляет:",
 o:["50 km/h","20 km/h","40 km/h"], o_ru:["50 км/ч","20 км/ч","40 км/ч"], a:0,
 e:"По таблице лимитов: Мотоциклу — 50 км/ч."},
{t:"velocidad", q:"En vía urbana de dos carriles por sentido, un turismo puede circular como máximo a:", q_ru:"По городской дороге с двумя полосами в одну сторону легковому автомобилю разрешено максимум:",
 o:["50 km/h","30 km/h","70 km/h"], o_ru:["50 км/ч","30 км/ч","70 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 50 км/ч."},
{t:"velocidad", q:"¿Cuál es la velocidad máxima de un turismo en vía urbana de dos carriles por sentido?", q_ru:"Какова максимальная скорость легковому автомобилю по городской дороге с двумя полосами в одну сторону?",
 o:["50 km/h","70 km/h","80 km/h"], o_ru:["50 км/ч","70 км/ч","80 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 50 км/ч."},
{t:"velocidad", q:"El límite de velocidad de un turismo en vía urbana de dos carriles por sentido es de:", q_ru:"Ограничение скорости легковому автомобилю по городской дороге с двумя полосами в одну сторону составляет:",
 o:["50 km/h","60 km/h","80 km/h"], o_ru:["50 км/ч","60 км/ч","80 км/ч"], a:0,
 e:"По таблице лимитов: Легковому автомобилю — 50 км/ч."},
{t:"multas", q:"¿Cuántos puntos se pierden por conducir sujetando el teléfono móvil con la mano?", q_ru:"Сколько баллов снимают за то, что держать телефон в руке за рулём?",
 o:["6 puntos","3 puntos","4 puntos"], o_ru:["6 баллов","3 балла","4 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"La sanción por conducir sujetando el teléfono móvil con la mano supone la pérdida de:", q_ru:"Наказание за то, что держать телефон в руке за рулём, отнимает:",
 o:["6 puntos","3 puntos","4 puntos"], o_ru:["6 баллов","3 балла","4 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"¿Cuántos puntos se pierden por conducir con una tasa de alcohol superior al doble de la permitida?", q_ru:"Сколько баллов снимают за то, что превысить норму алкоголя вдвое?",
 o:["6 puntos","3 puntos","4 puntos"], o_ru:["6 баллов","3 балла","4 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"La sanción por conducir con una tasa de alcohol superior al doble de la permitida supone la pérdida de:", q_ru:"Наказание за то, что превысить норму алкоголя вдвое, отнимает:",
 o:["6 puntos","3 puntos","4 puntos"], o_ru:["6 баллов","3 балла","4 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"¿Cuántos puntos se pierden por arrojar a la vía objetos que puedan provocar un incendio?", q_ru:"Сколько баллов снимают за то, что выбросить на дорогу то, что может вызвать пожар?",
 o:["6 puntos","4 puntos","2 puntos"], o_ru:["6 баллов","4 балла","2 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"La sanción por arrojar a la vía objetos que puedan provocar un incendio supone la pérdida de:", q_ru:"Наказание за то, что выбросить на дорогу то, что может вызвать пожар, отнимает:",
 o:["6 puntos","4 puntos","2 puntos"], o_ru:["6 баллов","4 балла","2 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"¿Cuántos puntos se pierden por conducir con presencia de drogas en el organismo?", q_ru:"Сколько баллов снимают за то, что сесть за руль с наркотиками в организме?",
 o:["6 puntos","3 puntos","2 puntos"], o_ru:["6 баллов","3 балла","2 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"La sanción por conducir con presencia de drogas en el organismo supone la pérdida de:", q_ru:"Наказание за то, что сесть за руль с наркотиками в организме, отнимает:",
 o:["6 puntos","3 puntos","2 puntos"], o_ru:["6 баллов","3 балла","2 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"¿Cuántos puntos se pierden por no utilizar el cinturón de seguridad?", q_ru:"Сколько баллов снимают за то, что не пристегнуть ремень?",
 o:["4 puntos","6 puntos","2 puntos"], o_ru:["4 балла","6 баллов","2 балла"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"La sanción por no utilizar el cinturón de seguridad supone la pérdida de:", q_ru:"Наказание за то, что не пристегнуть ремень, отнимает:",
 o:["4 puntos","6 puntos","2 puntos"], o_ru:["4 балла","6 баллов","2 балла"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"¿Cuántos puntos se pierden por no respetar un semáforo en rojo?", q_ru:"Сколько баллов снимают за то, что проехать на красный?",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"La sanción por no respetar un semáforo en rojo supone la pérdida de:", q_ru:"Наказание за то, что проехать на красный, отнимает:",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"¿Cuántos puntos se pierden por no respetar la prioridad de paso?", q_ru:"Сколько баллов снимают за то, что не уступить дорогу, когда обязан?",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"La sanción por no respetar la prioridad de paso supone la pérdida de:", q_ru:"Наказание за то, что не уступить дорогу, когда обязан, отнимает:",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"¿Cuántos puntos se pierden por adelantar poniendo en peligro a otros?", q_ru:"Сколько баллов снимают за то, что обогнать, создав опасность?",
 o:["4 puntos","6 puntos","2 puntos"], o_ru:["4 балла","6 баллов","2 балла"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"La sanción por adelantar poniendo en peligro a otros supone la pérdida de:", q_ru:"Наказание за то, что обогнать, создав опасность, отнимает:",
 o:["4 puntos","6 puntos","2 puntos"], o_ru:["4 балла","6 баллов","2 балла"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"¿Cuántos puntos se pierden por no utilizar el casco los motoristas?", q_ru:"Сколько баллов снимают за то, что мотоциклисту ехать без шлема?",
 o:["4 puntos","3 puntos","6 puntos"], o_ru:["4 балла","3 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"La sanción por no utilizar el casco los motoristas supone la pérdida de:", q_ru:"Наказание за то, что мотоциклисту ехать без шлема, отнимает:",
 o:["4 puntos","3 puntos","6 puntos"], o_ru:["4 балла","3 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"¿Cuántos puntos se pierden por circular marcha atrás en autopista?", q_ru:"Сколько баллов снимают за то, что ехать задним ходом по автомагистрали?",
 o:["6 puntos","4 puntos","2 puntos"], o_ru:["6 баллов","4 балла","2 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"La sanción por circular marcha atrás en autopista supone la pérdida de:", q_ru:"Наказание за то, что ехать задним ходом по автомагистрали, отнимает:",
 o:["6 puntos","4 puntos","2 puntos"], o_ru:["6 баллов","4 балла","2 балла"], a:0,
 e:"За это снимают 6."},
{t:"multas", q:"¿Cuántos puntos se pierden por no mantener la distancia de seguridad?", q_ru:"Сколько баллов снимают за то, что не держать дистанцию?",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"La sanción por no mantener la distancia de seguridad supone la pérdida de:", q_ru:"Наказание за то, что не держать дистанцию, отнимает:",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 4."},
{t:"multas", q:"¿Cuántos puntos se pierden por conducir utilizando auriculares conectados al móvil?", q_ru:"Сколько баллов снимают за то, что ехать в наушниках, подключённых к телефону?",
 o:["3 puntos","2 puntos","6 puntos"], o_ru:["3 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 3."},
{t:"multas", q:"La sanción por conducir utilizando auriculares conectados al móvil supone la pérdida de:", q_ru:"Наказание за то, что ехать в наушниках, подключённых к телефону, отнимает:",
 o:["3 puntos","2 puntos","6 puntos"], o_ru:["3 балла","2 балла","6 баллов"], a:0,
 e:"За это снимают 3."},
{t:"senales", s:"ceda_el_paso", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Ceder el paso a quien circula por la otra vía","Detenerse siempre del todo antes de la línea","Tener prioridad sobre la otra vía"], o_ru:["Уступить дорогу тем, кто едет по другой дороге","Всегда остановиться перед линией","Иметь приоритет над другой дорогой"], a:0,
 e:"Уступить дорогу тем, кто едет по другой дороге."},
{t:"senales", s:"ceda_el_paso", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Ceder el paso a quien circula por la otra vía","Detenerse siempre del todo antes de la línea","Tener prioridad sobre la otra vía"], o_ru:["Уступить дорогу тем, кто едет по другой дороге","Всегда остановиться перед линией","Иметь приоритет над другой дорогой"], a:0,
 e:"Уступить дорогу тем, кто едет по другой дороге."},
{t:"senales", s:"calzada_prioridad", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Circular por una vía con prioridad","Ceder el paso en todos los cruces","Entrar en una zona de prioridad peatonal"], o_ru:["Ехать по дороге с приоритетом","Уступать на всех перекрёстках","Въезжать в зону приоритета пешеходов"], a:0,
 e:"Ехать по дороге с приоритетом."},
{t:"senales", s:"calzada_prioridad", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Circular por una vía con prioridad","Ceder el paso en todos los cruces","Entrar en una zona de prioridad peatonal"], o_ru:["Ехать по дороге с приоритетом","Уступать на всех перекрёстках","Въезжать в зону приоритета пешеходов"], a:0,
 e:"Ехать по дороге с приоритетом."},
{t:"senales", s:"entrada_prohibida", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Entrada prohibida: es sentido contrario","Prohibido estacionar en todo ese lado","Calle cortada por obras en curso"], o_ru:["Въезд запрещён: там встречное движение","Стоянка на той стороне запрещена","Улица перекрыта из-за работ"], a:0,
 e:"Въезд запрещён: там встречное движение."},
{t:"senales", s:"entrada_prohibida", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Entrada prohibida: es sentido contrario","Prohibido estacionar en todo ese lado","Calle cortada por obras en curso"], o_ru:["Въезд запрещён: там встречное движение","Стоянка на той стороне запрещена","Улица перекрыта из-за работ"], a:0,
 e:"Въезд запрещён: там встречное движение."},
{t:"senales", s:"prohibido_camiones", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Prohibido el paso a camiones de mercancías","Prohibido el paso a autobuses de línea","Prohibido el paso con remolque pesado"], o_ru:["Проезд грузовиков запрещён","Проезд автобусов запрещён","Проезд с прицепом запрещён"], a:0,
 e:"Проезд грузовиков запрещён."},
{t:"senales", s:"prohibido_camiones", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Prohibido el paso a camiones de mercancías","Prohibido el paso a autobuses de línea","Prohibido el paso con remolque pesado"], o_ru:["Проезд грузовиков запрещён","Проезд автобусов запрещён","Проезд с прицепом запрещён"], a:0,
 e:"Проезд грузовиков запрещён."},
{t:"senales", s:"prohibido_bicicletas", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Prohibido el paso a bicicletas","Vía obligatoria para bicicletas","Aparcamiento reservado a bicicletas"], o_ru:["Проезд велосипедов запрещён","Дорожка, обязательная для велосипедов","Парковка для велосипедов"], a:0,
 e:"Проезд велосипедов запрещён."},
{t:"senales", s:"prohibido_bicicletas", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Prohibido el paso a bicicletas","Vía obligatoria para bicicletas","Aparcamiento reservado a bicicletas"], o_ru:["Проезд велосипедов запрещён","Дорожка, обязательная для велосипедов","Парковка для велосипедов"], a:0,
 e:"Проезд велосипедов запрещён."},
{t:"senales", s:"velocidad_maxima", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["No superar la velocidad indicada","Circular exactamente a esa velocidad","Velocidad recomendada en el tramo"], o_ru:["Не превышать указанную скорость","Ехать ровно с этой скоростью","Рекомендованная скорость на участке"], a:0,
 e:"Не превышать указанную скорость."},
{t:"senales", s:"velocidad_maxima", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["No superar la velocidad indicada","Circular exactamente a esa velocidad","Velocidad recomendada en el tramo"], o_ru:["Не превышать указанную скорость","Ехать ровно с этой скоростью","Рекомендованная скорость на участке"], a:0,
 e:"Не превышать указанную скорость."},
{t:"senales", s:"prohibido_adelantar", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Prohibido adelantar a otros vehículos","Prohibido circular en paralelo","Prohibido remolcar otro vehículo"], o_ru:["Обгон других машин запрещён","Запрещено ехать параллельно","Запрещено буксировать другую машину"], a:0,
 e:"Обгон других машин запрещён."},
{t:"senales", s:"prohibido_adelantar", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Prohibido adelantar a otros vehículos","Prohibido circular en paralelo","Prohibido remolcar otro vehículo"], o_ru:["Обгон других машин запрещён","Запрещено ехать параллельно","Запрещено буксировать другую машину"], a:0,
 e:"Обгон других машин запрещён."},
{t:"senales", s:"paso_obligatorio", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Paso obligatorio por ese lado","Prohibido pasar por ese lado","Carril reservado a autobuses"], o_ru:["Объезд обязателен с этой стороны","Проезд с этой стороны запрещён","Полоса только для автобусов"], a:0,
 e:"Объезд обязателен с этой стороны."},
{t:"senales", s:"paso_obligatorio", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Paso obligatorio por ese lado","Prohibido pasar por ese lado","Carril reservado a autobuses"], o_ru:["Объезд обязателен с этой стороны","Проезд с этой стороны запрещён","Полоса только для автобусов"], a:0,
 e:"Объезд обязателен с этой стороны."},
{t:"senales", s:"rotonda_obligatoria", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Glorieta: circular en el sentido indicado","Cruce donde está prohibido girar a la izquierda","Zona de maniobras para camiones"], o_ru:["Круговое: ехать в указанную сторону","Перекрёсток, где поворот запрещён","Зона для манёвров грузовиков"], a:0,
 e:"Круговое: ехать в указанную сторону."},
{t:"senales", s:"rotonda_obligatoria", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Glorieta: circular en el sentido indicado","Cruce donde está prohibido girar a la izquierda","Zona de maniobras para camiones"], o_ru:["Круговое: ехать в указанную сторону","Перекрёсток, где поворот запрещён","Зона для манёвров грузовиков"], a:0,
 e:"Круговое: ехать в указанную сторону."},
{t:"senales", s:"semaforo", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Semáforo más adelante","Zona vigilada con cámaras","Cruce regulado por un agente"], o_ru:["Светофор впереди","Зона с камерами наблюдения","Перекрёсток с регулировщиком"], a:0,
 e:"Светофор впереди."},
{t:"senales", s:"semaforo", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Semáforo más adelante","Zona vigilada con cámaras","Cruce regulado por un agente"], o_ru:["Светофор впереди","Зона с камерами наблюдения","Перекрёсток с регулировщиком"], a:0,
 e:"Светофор впереди."},
{t:"senales", s:"paso_nivel_barreras", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Paso a nivel con barreras","Zona de obras con vallas","Puente levadizo sobre el río"], o_ru:["Железнодорожный переезд со шлагбаумом","Зона работ с ограждением","Разводной мост через реку"], a:0,
 e:"Железнодорожный переезд со шлагбаумом."},
{t:"senales", s:"paso_nivel_barreras", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Paso a nivel con barreras","Zona de obras con vallas","Puente levadizo sobre el río"], o_ru:["Железнодорожный переезд со шлагбаумом","Зона работ с ограждением","Разводной мост через реку"], a:0,
 e:"Железнодорожный переезд со шлагбаумом."},
{t:"senales", s:"paso_nivel_sin_barreras", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Paso a nivel sin barreras","Estación de tren cercana","Paso subterráneo para trenes"], o_ru:["Переезд без шлагбаума","Железнодорожная станция рядом","Подземный переход для поездов"], a:0,
 e:"Переезд без шлагбаума."},
{t:"senales", s:"paso_nivel_sin_barreras", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Paso a nivel sin barreras","Estación de tren cercana","Paso subterráneo para trenes"], o_ru:["Переезд без шлагбаума","Железнодорожная станция рядом","Подземный переход для поездов"], a:0,
 e:"Переезд без шлагбаума."},
{t:"senales", s:"curva_derecha", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Curva peligrosa hacia la derecha","Desvío obligatorio a la derecha","Salida de vehículos por la derecha"], o_ru:["Опасный поворот направо","Обязательный объезд справа","Выезд машин справа"], a:0,
 e:"Опасный поворот направо."},
{t:"senales", s:"curva_derecha", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Curva peligrosa hacia la derecha","Desvío obligatorio a la derecha","Salida de vehículos por la derecha"], o_ru:["Опасный поворот направо","Обязательный объезд справа","Выезд машин справа"], a:0,
 e:"Опасный поворот направо."},
{t:"senales", s:"curva_izquierda", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Curva peligrosa hacia la izquierda","Desvío obligatorio a la izquierda","Salida de vehículos por la izquierda"], o_ru:["Опасный поворот налево","Обязательный объезд слева","Выезд машин слева"], a:0,
 e:"Опасный поворот налево."},
{t:"senales", s:"curva_izquierda", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Curva peligrosa hacia la izquierda","Desvío obligatorio a la izquierda","Salida de vehículos por la izquierda"], o_ru:["Опасный поворот налево","Обязательный объезд слева","Выезд машин слева"], a:0,
 e:"Опасный поворот налево."},
{t:"senales", s:"baden", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Resalto o badén en la calzada","Cambio de rasante sin visibilidad","Paso superior para peatones"], o_ru:["Искусственная неровность на дороге","Перелом дороги без видимости","Надземный переход"], a:0,
 e:"Искусственная неровность на дороге."},
{t:"senales", s:"baden", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Resalto o badén en la calzada","Cambio de rasante sin visibilidad","Paso superior para peatones"], o_ru:["Искусственная неровность на дороге","Перелом дороги без видимости","Надземный переход"], a:0,
 e:"Искусственная неровность на дороге."},
{t:"senales", s:"estrechamiento", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Estrechamiento de la calzada","Túnel estrecho sin iluminación","Puente con carga limitada"], o_ru:["Сужение проезжей части","Узкий неосвещённый туннель","Мост с ограничением нагрузки"], a:0,
 e:"Сужение проезжей части."},
{t:"senales", s:"estrechamiento", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Estrechamiento de la calzada","Túnel estrecho sin iluminación","Puente con carga limitada"], o_ru:["Сужение проезжей части","Узкий неосвещённый туннель","Мост с ограничением нагрузки"], a:0,
 e:"Сужение проезжей части."},
{t:"senales", s:"obras_temporal", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Obras: señal temporal que prevalece","Señal informativa sin obligación","Señal que puede ignorarse"], o_ru:["Работы: временный знак, он главнее","Информационный знак без обязанности","Знак, который можно не выполнять"], a:0,
 e:"Работы: временный знак, он главнее."},
{t:"senales", s:"obras_temporal", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Obras: señal temporal que prevalece","Señal informativa sin obligación","Señal que puede ignorarse"], o_ru:["Работы: временный знак, он главнее","Информационный знак без обязанности","Знак, который можно не выполнять"], a:0,
 e:"Работы: временный знак, он главнее."},
{t:"senales", s:"peatones_peligro", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Peligro por paso de peatones","Zona peatonal cerrada al tráfico","Parada de autobús escolar"], o_ru:["Опасность: пешеходы","Пешеходная зона без машин","Остановка школьного автобуса"], a:0,
 e:"Опасность: пешеходы."},
{t:"senales", s:"peatones_peligro", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Peligro por paso de peatones","Zona peatonal cerrada al tráfico","Parada de autobús escolar"], o_ru:["Опасность: пешеходы","Пешеходная зона без машин","Остановка школьного автобуса"], a:0,
 e:"Опасность: пешеходы."},
{t:"senales", s:"ciclistas_peligro", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Paso frecuente de ciclistas","Carril reservado a bicicletas","Prohibición de circular en bici"], o_ru:["Частое появление велосипедистов","Полоса для велосипедов","Запрет ездить на велосипеде"], a:0,
 e:"Частое появление велосипедистов."},
{t:"senales", s:"ciclistas_peligro", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Paso frecuente de ciclistas","Carril reservado a bicicletas","Prohibición de circular en bici"], o_ru:["Частое появление велосипедистов","Полоса для велосипедов","Запрет ездить на велосипеде"], a:0,
 e:"Частое появление велосипедистов."},
{t:"senales", s:"otros_peligros", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Un peligro que no tiene señal propia","Avería habitual de los semáforos","Tramo con control por radar"], o_ru:["Опасность, у которой нет своего знака","Частая поломка светофоров","Участок с камерой контроля"], a:0,
 e:"Опасность, у которой нет своего знака."},
{t:"senales", s:"otros_peligros", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Un peligro que no tiene señal propia","Avería habitual de los semáforos","Tramo con control por radar"], o_ru:["Опасность, у которой нет своего знака","Частая поломка светофоров","Участок с камерой контроля"], a:0,
 e:"Опасность, у которой нет своего знака."},
{t:"senales", s:"paso_peatones", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Paso de peatones: ahí tienen prioridad","Acera elevada sobre la calzada","Camino reservado sólo a peatones"], o_ru:["Пешеходный переход: там у них приоритет","Приподнятый тротуар для пешеходов","Дорожка только для пешеходов"], a:0,
 e:"Пешеходный переход: там у них приоритет."},
{t:"senales", s:"paso_peatones", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Paso de peatones: ahí tienen prioridad","Acera elevada sobre la calzada","Camino reservado sólo a peatones"], o_ru:["Пешеходный переход: там у них приоритет","Приподнятый тротуар для пешеходов","Дорожка только для пешеходов"], a:0,
 e:"Пешеходный переход: там у них приоритет."},
{t:"senales", s:"marca_discontinua", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Puede rebasarse para adelantar o cambiar de carril","No puede rebasarse ni pisarse en ningún caso","Sólo pueden rebasarla motos y bicicletas"], o_ru:["Можно пересекать для обгона и смены полосы","Нельзя пересекать ни при каких условиях","Пересекать могут только мотоциклы"], a:0,
 e:"Можно пересекать для обгона и смены полосы."},
{t:"senales", s:"marca_discontinua", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Puede rebasarse para adelantar o cambiar de carril","No puede rebasarse ni pisarse en ningún caso","Sólo pueden rebasarla motos y bicicletas"], o_ru:["Можно пересекать для обгона и смены полосы","Нельзя пересекать ни при каких условиях","Пересекать могут только мотоциклы"], a:0,
 e:"Можно пересекать для обгона и смены полосы."},
{t:"senales", s:"marca_zigzag", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Prohibido estacionar junto al bordillo","Zona de carga y descarga","Aparcamiento libre para residentes"], o_ru:["Стоянка у бордюра запрещена","Зона погрузки и разгрузки","Свободная парковка для местных"], a:0,
 e:"Стоянка у бордюра запрещена."},
{t:"senales", s:"marca_zigzag", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Prohibido estacionar junto al bordillo","Zona de carga y descarga","Aparcamiento libre para residentes"], o_ru:["Стоянка у бордюра запрещена","Зона погрузки и разгрузки","Свободная парковка для местных"], a:0,
 e:"Стоянка у бордюра запрещена."},
{t:"senales", s:"semaforo_ambar_intermitente", q:"¿Qué significa esta señal?", q_ru:"Что означает этот знак?",
 o:["Pasar con precaución: rige la señalización","Detenerse por completo y esperar el verde","Que el semáforo está averiado del todo"], o_ru:["Ехать осторожно: действуют знаки","Полностью остановиться и ждать","Что светофор сломан"], a:0,
 e:"Ехать осторожно: действуют знаки."},
{t:"senales", s:"semaforo_ambar_intermitente", q:"Al ver esta señal sabes que:", q_ru:"Увидев этот знак, ты знаешь, что:",
 o:["Pasar con precaución: rige la señalización","Detenerse por completo y esperar el verde","Que el semáforo está averiado del todo"], o_ru:["Ехать осторожно: действуют знаки","Полностью остановиться и ждать","Что светофор сломан"], a:0,
 e:"Ехать осторожно: действуют знаки."},
{t:"seguridad", q:"A 30 km/h, ¿cuántos metros recorre el coche en un segundo de reacción?", q_ru:"На скорости 30 км/ч сколько метров машина проезжает за секунду реакции?",
 o:["Unos 8 metros","Unos 5 metros","Unos 12 metros"], o_ru:["Около 8 метров","Около 5 метров","Около 12 метров"], a:0,
 e:"Скорость делить на 3,6 — это метры за секунду: 30 км/ч дают 8 м."},
{t:"seguridad", q:"A 50 km/h, ¿cuántos metros recorre el coche en un segundo de reacción?", q_ru:"На скорости 50 км/ч сколько метров машина проезжает за секунду реакции?",
 o:["Unos 14 metros","Unos 8 metros","Unos 21 metros"], o_ru:["Около 14 метров","Около 8 метров","Около 21 метров"], a:0,
 e:"Скорость делить на 3,6 — это метры за секунду: 50 км/ч дают 14 м."},
{t:"seguridad", q:"A 80 km/h, ¿cuántos metros recorre el coche en un segundo de reacción?", q_ru:"На скорости 80 км/ч сколько метров машина проезжает за секунду реакции?",
 o:["Unos 22 metros","Unos 13 metros","Unos 33 metros"], o_ru:["Около 22 метров","Около 13 метров","Около 33 метров"], a:0,
 e:"Скорость делить на 3,6 — это метры за секунду: 80 км/ч дают 22 м."},
{t:"seguridad", q:"A 90 km/h, ¿cuántos metros recorre el coche en un segundo de reacción?", q_ru:"На скорости 90 км/ч сколько метров машина проезжает за секунду реакции?",
 o:["Unos 25 metros","Unos 15 metros","Unos 38 metros"], o_ru:["Около 25 метров","Около 15 метров","Около 38 метров"], a:0,
 e:"Скорость делить на 3,6 — это метры за секунду: 90 км/ч дают 25 м."},
{t:"seguridad", q:"A 100 km/h, ¿cuántos metros recorre el coche en un segundo de reacción?", q_ru:"На скорости 100 км/ч сколько метров машина проезжает за секунду реакции?",
 o:["Unos 28 metros","Unos 17 metros","Unos 42 metros"], o_ru:["Около 28 метров","Около 17 метров","Около 42 метров"], a:0,
 e:"Скорость делить на 3,6 — это метры за секунду: 100 км/ч дают 28 м."},
{t:"seguridad", q:"A 120 km/h, ¿cuántos metros recorre el coche en un segundo de reacción?", q_ru:"На скорости 120 км/ч сколько метров машина проезжает за секунду реакции?",
 o:["Unos 33 metros","Unos 20 metros","Unos 50 metros"], o_ru:["Около 33 метров","Около 20 метров","Около 50 метров"], a:0,
 e:"Скорость делить на 3,6 — это метры за секунду: 120 км/ч дают 33 м."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en aire espirado para un conductor con más de dos años de permiso?", q_ru:"Какова максимальная норма алкоголя в выдыхаемом воздухе для водителя со стажем больше двух лет?",
 o:["0,25 mg/l","0,15 mg/l","0,30 mg/l"], o_ru:["0,25 мг/л","0,15 мг/л","0,30 мг/л"], a:0,
 e:"Для водителя со стажем больше двух лет норма в воздухе — 0,25 мг/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en sangre para un conductor con más de dos años de permiso?", q_ru:"Какова максимальная норма алкоголя в крови для водителя со стажем больше двух лет?",
 o:["0,5 g/l","0,3 g/l","0,8 g/l"], o_ru:["0,5 г/л","0,3 г/л","0,8 г/л"], a:0,
 e:"Для водителя со стажем больше двух лет норма в крови — 0,5 г/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en aire espirado para un conductor novel (menos de dos años)?", q_ru:"Какова максимальная норма алкоголя в выдыхаемом воздухе для начинающего водителя (меньше двух лет)?",
 o:["0,15 mg/l","0,25 mg/l","0,30 mg/l"], o_ru:["0,15 мг/л","0,25 мг/л","0,30 мг/л"], a:0,
 e:"Для начинающего водителя (меньше двух лет) норма в воздухе — 0,15 мг/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en sangre para un conductor novel (menos de dos años)?", q_ru:"Какова максимальная норма алкоголя в крови для начинающего водителя (меньше двух лет)?",
 o:["0,3 g/l","0,5 g/l","0,8 g/l"], o_ru:["0,3 г/л","0,5 г/л","0,8 г/л"], a:0,
 e:"Для начинающего водителя (меньше двух лет) норма в крови — 0,3 г/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en aire espirado para un conductor profesional?", q_ru:"Какова максимальная норма алкоголя в выдыхаемом воздухе для профессионального водителя?",
 o:["0,15 mg/l","0,25 mg/l","0,30 mg/l"], o_ru:["0,15 мг/л","0,25 мг/л","0,30 мг/л"], a:0,
 e:"Для профессионального водителя норма в воздухе — 0,15 мг/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en sangre para un conductor profesional?", q_ru:"Какова максимальная норма алкоголя в крови для профессионального водителя?",
 o:["0,3 g/l","0,5 g/l","0,8 g/l"], o_ru:["0,3 г/л","0,5 г/л","0,8 г/л"], a:0,
 e:"Для профессионального водителя норма в крови — 0,3 г/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en aire espirado para un conductor de autobús escolar?", q_ru:"Какова максимальная норма алкоголя в выдыхаемом воздухе для водителя школьного автобуса?",
 o:["0,15 mg/l","0,25 mg/l","0,30 mg/l"], o_ru:["0,15 мг/л","0,25 мг/л","0,30 мг/л"], a:0,
 e:"Для водителя школьного автобуса норма в воздухе — 0,15 мг/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en sangre para un conductor de autobús escolar?", q_ru:"Какова максимальная норма алкоголя в крови для водителя школьного автобуса?",
 o:["0,3 g/l","0,5 g/l","0,8 g/l"], o_ru:["0,3 г/л","0,5 г/л","0,8 г/л"], a:0,
 e:"Для водителя школьного автобуса норма в крови — 0,3 г/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en aire espirado para un ciclista?", q_ru:"Какова максимальная норма алкоголя в выдыхаемом воздухе для велосипедиста?",
 o:["0,25 mg/l","0,15 mg/l","0,30 mg/l"], o_ru:["0,25 мг/л","0,15 мг/л","0,30 мг/л"], a:0,
 e:"Для велосипедиста норма в воздухе — 0,25 мг/л."},
{t:"alcohol", q:"¿Cuál es la tasa máxima de alcohol en sangre para un ciclista?", q_ru:"Какова максимальная норма алкоголя в крови для велосипедиста?",
 o:["0,5 g/l","0,3 g/l","0,8 g/l"], o_ru:["0,5 г/л","0,3 г/л","0,8 г/л"], a:0,
 e:"Для велосипедиста норма в крови — 0,5 г/л."},
{t:"documentos", q:"¿A partir de qué edad se puede obtener el permiso AM?", q_ru:"С какого возраста можно получить категорию AM?",
 o:["15 años","14 años","16 años"], o_ru:["15 лет","14 лет","16 лет"], a:0,
 e:"Категория AM — с 15 лет (мопеды до 45 км/ч)."},
{t:"documentos", q:"¿Qué permite conducir el permiso AM?", q_ru:"Что разрешает категория AM?",
 o:["Ciclomotores de hasta 45 km/h","Motos ligeras de hasta 125 cc","Motos de potencia media limitada"], o_ru:["Мопеды до 45 км/ч","Лёгкие мотоциклы до 125 кубиков","Мотоциклы средней мощности"], a:0,
 e:"Категория AM — это мопеды до 45 км/ч."},
{t:"documentos", q:"¿A partir de qué edad se puede obtener el permiso A1?", q_ru:"С какого возраста можно получить категорию A1?",
 o:["16 años","14 años","15 años"], o_ru:["16 лет","14 лет","15 лет"], a:0,
 e:"Категория A1 — с 16 лет (лёгкие мотоциклы до 125 кубиков)."},
{t:"documentos", q:"¿Qué permite conducir el permiso A1?", q_ru:"Что разрешает категория A1?",
 o:["Motos ligeras de hasta 125 cc","Ciclomotores de hasta 45 km/h","Motos de potencia media limitada"], o_ru:["Лёгкие мотоциклы до 125 кубиков","Мопеды до 45 км/ч","Мотоциклы средней мощности"], a:0,
 e:"Категория A1 — это лёгкие мотоциклы до 125 кубиков."},
{t:"documentos", q:"¿A partir de qué edad se puede obtener el permiso A2?", q_ru:"С какого возраста можно получить категорию A2?",
 o:["18 años","14 años","15 años"], o_ru:["18 лет","14 лет","15 лет"], a:0,
 e:"Категория A2 — с 18 лет (мотоциклы средней мощности)."},
{t:"documentos", q:"¿Qué permite conducir el permiso A2?", q_ru:"Что разрешает категория A2?",
 o:["Motos de potencia media limitada","Ciclomotores de hasta 45 km/h","Motos ligeras de hasta 125 cc"], o_ru:["Мотоциклы средней мощности","Мопеды до 45 км/ч","Лёгкие мотоциклы до 125 кубиков"], a:0,
 e:"Категория A2 — это мотоциклы средней мощности."},
{t:"documentos", q:"¿A partir de qué edad se puede obtener el permiso B?", q_ru:"С какого возраста можно получить категорию B?",
 o:["18 años","14 años","15 años"], o_ru:["18 лет","14 лет","15 лет"], a:0,
 e:"Категория B — с 18 лет (легковые до 3500 кг)."},
{t:"documentos", q:"¿Qué permite conducir el permiso B?", q_ru:"Что разрешает категория B?",
 o:["Turismos de hasta 3.500 kg","Ciclomotores de hasta 45 km/h","Motos ligeras de hasta 125 cc"], o_ru:["Легковые до 3500 кг","Мопеды до 45 км/ч","Лёгкие мотоциклы до 125 кубиков"], a:0,
 e:"Категория B — это легковые до 3500 кг."},
{t:"documentos", q:"¿Cuál es la validez del examen teórico aprobado?", q_ru:"Какова периодичность: годность сданной теории?",
 o:["Dos años","Seis meses","Cinco años"], o_ru:["Два года","Полгода","Пять лет"], a:0,
 e:"Годность сданной теории — два года."},
{t:"documentos", q:"¿Cuál es la renovación del permiso B antes de los 65 años?", q_ru:"Какова периодичность: продление категории B до 65 лет?",
 o:["Cada diez años","Cada cinco años","Cada quince años"], o_ru:["Каждые десять лет","Каждые пять лет","Каждые пятнадцать лет"], a:0,
 e:"Продление категории b до 65 лет — каждые десять лет."},
{t:"documentos", q:"¿Cuál es la renovación del permiso B después de los 65 años?", q_ru:"Какова периодичность: продление категории B после 65 лет?",
 o:["Cada cinco años","Cada diez años","Cada dos años"], o_ru:["Каждые пять лет","Каждые десять лет","Каждые два года"], a:0,
 e:"Продление категории b после 65 лет — каждые пять лет."},
{t:"documentos", q:"¿Cuál es la ITV de un turismo de cuatro a diez años?", q_ru:"Какова периодичность: техосмотр легковой машины 4-10 лет?",
 o:["Cada dos años","Cada año","Cada cuatro años"], o_ru:["Каждые два года","Ежегодно","Каждые четыре года"], a:0,
 e:"Техосмотр легковой машины 4-10 лет — каждые два года."},
{t:"documentos", q:"¿Cuál es la ITV de un turismo de más de diez años?", q_ru:"Какова периодичность: техосмотр легковой машины старше десяти лет?",
 o:["Cada año","Cada dos años","Cada seis meses"], o_ru:["Ежегодно","Каждые два года","Каждые полгода"], a:0,
 e:"Техосмотр легковой машины старше десяти лет — ежегодно."},
{t:"documentos", q:"¿Cuál es el plazo para pagar una multa con descuento?", q_ru:"Каков срок оплаты штрафа со скидкой?",
 o:["Veinte días naturales","Diez días naturales","Dos meses"], o_ru:["Двадцать календарных дней","Десять календарных дней","Два месяца"], a:0,
 e:"Срок оплаты штрафа со скидкой — двадцать календарных дней."},
{t:"documentos", q:"¿Cuál es el plazo para recurrir una multa?", q_ru:"Каков срок обжалования штрафа?",
 o:["Veinte días naturales","Cinco días naturales","Tres meses"], o_ru:["Двадцать календарных дней","Пять календарных дней","Три месяца"], a:0,
 e:"Срок обжалования штрафа — двадцать календарных дней."},
{t:"documentos", q:"¿Cuál es el tiempo sin infracciones graves para recuperar todos los puntos?", q_ru:"Каков срок без серьёзных нарушений для возврата всех баллов?",
 o:["Dos años","Seis meses","Cuatro años"], o_ru:["Два года","Полгода","Четыре года"], a:0,
 e:"Срок без серьёзных нарушений для возврата всех баллов — два года."},
{t:"documentos", q:"¿Cuál es la duración del curso de recuperación parcial de puntos?", q_ru:"Какова периодичность: длительность курса частичного восстановления баллов?",
 o:["Doce horas","Cuatro horas","Veinticuatro horas"], o_ru:["Двенадцать часов","Четыре часа","Двадцать четыре часа"], a:0,
 e:"Длительность курса частичного восстановления баллов — двенадцать часов."},
{t:"documentos", q:"¿Cuál es el plazo para hacer el examen práctico tras aprobar el teórico?", q_ru:"Каков срок сдачи практики после теории?",
 o:["Dos años","Seis meses","Un año"], o_ru:["Два года","Полгода","Один год"], a:0,
 e:"Срок сдачи практики после теории — два года."},
{t:"seguridad", q:"¿Qué luces se utilizan con niebla densa de día?", q_ru:"Какой свет включают в густом тумане днём?",
 o:["Luz de niebla y luz de cruce","Luz de carretera y de posición","Sólo las luces de posición"], o_ru:["Противотуманные и ближний свет","Дальний и габариты","Только габариты"], a:0,
 e:"В густом тумане днём: противотуманные и ближний свет."},
{t:"seguridad", q:"¿Qué luces se utilizan al circular por un túnel iluminado?", q_ru:"Какой свет включают при проезде освещённого туннеля?",
 o:["Luz de cruce encendida","Sólo las luces de posición","Luz de carretera encendida"], o_ru:["Включённый ближний свет","Только габариты","Включённый дальний свет"], a:0,
 e:"При проезде освещённого туннеля: включённый ближний свет."},
{t:"seguridad", q:"¿Qué luces se utilizan al cruzarse con otro vehículo de noche?", q_ru:"Какой свет включают при встрече с машиной ночью?",
 o:["Cambiar a luz de cruce","Mantener la luz de carretera","Apagar todas las luces"], o_ru:["Переключиться на ближний","Оставить дальний","Выключить весь свет"], a:0,
 e:"При встрече с машиной ночью: переключиться на ближний."},
{t:"seguridad", q:"¿Qué luces se utilizan al detenerse en el arcén de noche?", q_ru:"Какой свет включают при остановке на обочине ночью?",
 o:["Luces de posición y emergencia","Luz de carretera encendida","Todas las luces apagadas"], o_ru:["Габариты и аварийка","Включённый дальний","Весь свет выключен"], a:0,
 e:"При остановке на обочине ночью: габариты и аварийка."},
{t:"multas", q:"¿Cuál es el importe habitual de una infracción leve?", q_ru:"Каков обычный размер штрафа за лёгкое нарушение?",
 o:["100 euros","200 euros","500 euros"], o_ru:["100 евро","200 евро","500 евро"], a:0,
 e:"Лёгкое нарушение — 100 евро."},
{t:"multas", q:"¿Cuál es el importe habitual de una infracción grave?", q_ru:"Каков обычный размер штрафа за серьёзное нарушение?",
 o:["200 euros","100 euros","500 euros"], o_ru:["200 евро","100 евро","500 евро"], a:0,
 e:"Серьёзное нарушение — 200 евро."},
{t:"multas", q:"¿Cuál es el importe habitual de una infracción muy grave?", q_ru:"Каков обычный размер штрафа за особо тяжкое нарушение?",
 o:["500 euros","100 euros","200 euros"], o_ru:["500 евро","100 евро","200 евро"], a:0,
 e:"Особо тяжкое нарушение — 500 евро."},
{t:"prioridad", q:"¿Quién cede el paso en una glorieta?", q_ru:"Кто уступает дорогу на круговом движении?",
 o:["Ceden los que entran en ella","Ceden los que ya circulan dentro","Cede siempre el vehículo más lento"], o_ru:["Уступают те, кто въезжает","Уступают те, кто уже внутри","Уступает самая медленная машина"], a:0,
 e:"На круговом движении: уступают те, кто въезжает."},
{t:"prioridad", q:"La prioridad en una glorieta funciona así:", q_ru:"Приоритет на круговом движении работает так:",
 o:["Ceden los que entran en ella","Ceden los que ya circulan dentro","Cede siempre el vehículo más lento"], o_ru:["Уступают те, кто въезжает","Уступают те, кто уже внутри","Уступает самая медленная машина"], a:0,
 e:"На круговом движении: уступают те, кто въезжает."},
{t:"prioridad", q:"¿Quién cede el paso en un cruce sin señales?", q_ru:"Кто уступает дорогу на перекрёстке без знаков?",
 o:["Cede quien tiene un vehículo a su derecha","Cede quien circula en línea recta hacia el cruce","Cede el vehículo de menor tamaño"], o_ru:["Уступает тот, у кого машина справа","Уступает тот, кто едет прямо","Уступает машина поменьше"], a:0,
 e:"На перекрёстке без знаков: уступает тот, у кого машина справа."},
{t:"prioridad", q:"La prioridad en un cruce sin señales funciona así:", q_ru:"Приоритет на перекрёстке без знаков работает так:",
 o:["Cede quien tiene un vehículo a su derecha","Cede quien circula en línea recta hacia el cruce","Cede el vehículo de menor tamaño"], o_ru:["Уступает тот, у кого машина справа","Уступает тот, кто едет прямо","Уступает машина поменьше"], a:0,
 e:"На перекрёстке без знаков: уступает тот, у кого машина справа."},
{t:"prioridad", q:"¿Quién cede el paso al salir de un aparcamiento?", q_ru:"Кто уступает дорогу при выезде с парковки?",
 o:["Cede el que sale a todos los demás","Ceden los que circulan por la vía","Pasa primero quien llegue antes"], o_ru:["Выезжающий уступает всем","Уступают те, кто едет по дороге","Первым едет подъехавший раньше"], a:0,
 e:"При выезде с парковки: выезжающий уступает всем."},
{t:"prioridad", q:"La prioridad al salir de un aparcamiento funciona así:", q_ru:"Приоритет при выезде с парковки работает так:",
 o:["Cede el que sale a todos los demás","Ceden los que circulan por la vía","Pasa primero quien llegue antes"], o_ru:["Выезжающий уступает всем","Уступают те, кто едет по дороге","Первым едет подъехавший раньше"], a:0,
 e:"При выезде с парковки: выезжающий уступает всем."},
{t:"prioridad", q:"¿Quién cede el paso ante un vehículo de emergencia con sirena?", q_ru:"Кто уступает дорогу перед спецтранспортом с сиреной?",
 o:["Todos le facilitan el paso","Sólo ceden los que van detrás","Nadie está obligado a cederle"], o_ru:["Все освобождают ему дорогу","Уступают только едущие сзади","Никто не обязан уступать"], a:0,
 e:"Перед спецтранспортом с сиреной: все освобождают ему дорогу."},
{t:"prioridad", q:"La prioridad ante un vehículo de emergencia con sirena funciona así:", q_ru:"Приоритет перед спецтранспортом с сиреной работает так:",
 o:["Todos le facilitan el paso","Sólo ceden los que van detrás","Nadie está obligado a cederle"], o_ru:["Все освобождают ему дорогу","Уступают только едущие сзади","Никто не обязан уступать"], a:0,
 e:"Перед спецтранспортом с сиреной: все освобождают ему дорогу."},
{t:"prioridad", q:"¿Quién cede el paso ante un tranvía en la calzada?", q_ru:"Кто уступает дорогу перед трамваем на проезжей части?",
 o:["El tranvía pasa primero siempre","El tranvía cede en los cruces","Pasa primero quien llegue antes"], o_ru:["Трамвай проезжает первым всегда","Трамвай уступает на перекрёстках","Первым едет подъехавший раньше"], a:0,
 e:"Перед трамваем на проезжей части: трамвай проезжает первым всегда."},
{t:"prioridad", q:"La prioridad ante un tranvía en la calzada funciona así:", q_ru:"Приоритет перед трамваем на проезжей части работает так:",
 o:["El tranvía pasa primero siempre","El tranvía cede en los cruces","Pasa primero quien llegue antes"], o_ru:["Трамвай проезжает первым всегда","Трамвай уступает на перекрёстках","Первым едет подъехавший раньше"], a:0,
 e:"Перед трамваем на проезжей части: трамвай проезжает первым всегда."},
{t:"prioridad", q:"¿Quién cede el paso al incorporarse por un carril de aceleración?", q_ru:"Кто уступает дорогу при выезде по полосе разгона?",
 o:["Cede quien se incorpora a la vía","Ceden los que ya van por la vía","Pasa primero el más rápido"], o_ru:["Уступает тот, кто вливается","Уступают те, кто уже едет","Первым едет самый быстрый"], a:0,
 e:"При выезде по полосе разгона: уступает тот, кто вливается."},
{t:"prioridad", q:"La prioridad al incorporarse por un carril de aceleración funciona así:", q_ru:"Приоритет при выезде по полосе разгона работает так:",
 o:["Cede quien se incorpora a la vía","Ceden los que ya van por la vía","Pasa primero el más rápido"], o_ru:["Уступает тот, кто вливается","Уступают те, кто уже едет","Первым едет самый быстрый"], a:0,
 e:"При выезде по полосе разгона: уступает тот, кто вливается."},
{t:"prioridad", q:"¿Quién cede el paso al hacer un cambio de sentido?", q_ru:"Кто уступает дорогу при развороте?",
 o:["Cede a todos, vengan de donde vengan","Sólo cede a los que vienen de frente","Tiene preferencia por ser maniobra"], o_ru:["Уступает всем, откуда бы ни ехали","Уступает только встречным","Имеет приоритет как манёвр"], a:0,
 e:"При развороте: уступает всем, откуда бы ни ехали."},
{t:"prioridad", q:"La prioridad al hacer un cambio de sentido funciona así:", q_ru:"Приоритет при развороте работает так:",
 o:["Cede a todos, vengan de donde vengan","Sólo cede a los que vienen de frente","Tiene preferencia por ser maniobra"], o_ru:["Уступает всем, откуда бы ни ехали","Уступает только встречным","Имеет приоритет как манёвр"], a:0,
 e:"При развороте: уступает всем, откуда бы ни ехали."},
{t:"prioridad", q:"¿Quién cede el paso al circular marcha atrás?", q_ru:"Кто уступает дорогу при движении задним ходом?",
 o:["Cede el paso a todos los demás","Mantiene la preferencia que tenía","Tiene preferencia sobre los peatones"], o_ru:["Уступает всем остальным","Сохраняет прежний приоритет","Имеет приоритет над пешеходами"], a:0,
 e:"При движении задним ходом: уступает всем остальным."},
{t:"prioridad", q:"La prioridad al circular marcha atrás funciona así:", q_ru:"Приоритет при движении задним ходом работает так:",
 o:["Cede el paso a todos los demás","Mantiene la preferencia que tenía","Tiene preferencia sobre los peatones"], o_ru:["Уступает всем остальным","Сохраняет прежний приоритет","Имеет приоритет над пешеходами"], a:0,
 e:"При движении задним ходом: уступает всем остальным."},
{t:"prioridad", q:"¿Quién cede el paso ante un autobús que sale de su parada en ciudad?", q_ru:"Кто уступает дорогу перед автобусом от остановки в городе?",
 o:["Se le cede el paso al autobús","El autobús cede a todo el mundo","Pasa primero quien llegue antes"], o_ru:["Автобусу уступают дорогу","Автобус уступает всем","Первым едет подъехавший раньше"], a:0,
 e:"Перед автобусом от остановки в городе: автобусу уступают дорогу."},
{t:"prioridad", q:"La prioridad ante un autobús que sale de su parada en ciudad funciona así:", q_ru:"Приоритет перед автобусом от остановки в городе работает так:",
 o:["Se le cede el paso al autobús","El autobús cede a todo el mundo","Pasa primero quien llegue antes"], o_ru:["Автобусу уступают дорогу","Автобус уступает всем","Первым едет подъехавший раньше"], a:0,
 e:"Перед автобусом от остановки в городе: автобусу уступают дорогу."},
{t:"prioridad", q:"¿Quién cede el paso en una pendiente estrecha?", q_ru:"Кто уступает дорогу на узком подъёме?",
 o:["Cede quien baja la pendiente","Cede quien sube la pendiente","Cede el vehículo más pesado"], o_ru:["Уступает едущий вниз","Уступает едущий вверх","Уступает более тяжёлая машина"], a:0,
 e:"На узком подъёме: уступает едущий вниз."},
{t:"prioridad", q:"La prioridad en una pendiente estrecha funciona así:", q_ru:"Приоритет на узком подъёме работает так:",
 o:["Cede quien baja la pendiente","Cede quien sube la pendiente","Cede el vehículo más pesado"], o_ru:["Уступает едущий вниз","Уступает едущий вверх","Уступает более тяжёлая машина"], a:0,
 e:"На узком подъёме: уступает едущий вниз."},
{t:"prioridad", q:"¿Quién cede el paso ante un peatón en un paso sin semáforo?", q_ru:"Кто уступает дорогу перед пешеходом на зебре без светофора?",
 o:["El peatón tiene prioridad siempre","El peatón espera a que pase el coche","El peatón sólo tiene prioridad de día"], o_ru:["Пешеход имеет приоритет всегда","Пешеход ждёт, пока проедет машина","Пешеход главнее только днём"], a:0,
 e:"Перед пешеходом на зебре без светофора: пешеход имеет приоритет всегда."},
{t:"prioridad", q:"La prioridad ante un peatón en un paso sin semáforo funciona así:", q_ru:"Приоритет перед пешеходом на зебре без светофора работает так:",
 o:["El peatón tiene prioridad siempre","El peatón espera a que pase el coche","El peatón sólo tiene prioridad de día"], o_ru:["Пешеход имеет приоритет всегда","Пешеход ждёт, пока проедет машина","Пешеход главнее только днём"], a:0,
 e:"Перед пешеходом на зебре без светофора: пешеход имеет приоритет всегда."},
{t:"prioridad", q:"¿Quién cede el paso al girar cruzando un carril bici?", q_ru:"Кто уступает дорогу при повороте через велополосу?",
 o:["Cede el paso a los ciclistas","Los ciclistas ceden al coche","Pasa primero quien llegue antes"], o_ru:["Уступает велосипедистам","Велосипедисты уступают машине","Первым едет подъехавший раньше"], a:0,
 e:"При повороте через велополосу: уступает велосипедистам."},
{t:"prioridad", q:"La prioridad al girar cruzando un carril bici funciona así:", q_ru:"Приоритет при повороте через велополосу работает так:",
 o:["Cede el paso a los ciclistas","Los ciclistas ceden al coche","Pasa primero quien llegue antes"], o_ru:["Уступает велосипедистам","Велосипедисты уступают машине","Первым едет подъехавший раньше"], a:0,
 e:"При повороте через велополосу: уступает велосипедистам."},
{t:"seguridad", q:"¿Qué norma rige para el cinturón de seguridad?", q_ru:"Какое правило действует для «ремень безопасности»?",
 o:["Obligatorio en todas las plazas","Obligatorio sólo delante","Obligatorio sólo fuera de ciudad"], o_ru:["Обязателен на всех местах","Обязателен только спереди","Обязателен только за городом"], a:0,
 e:"Ремень безопасности: обязателен на всех местах."},
{t:"seguridad", q:"¿Qué norma rige para el casco en moto?", q_ru:"Какое правило действует для «шлем на мотоцикле»?",
 o:["Obligatorio siempre, también en ciudad","Obligatorio sólo fuera de poblado","Obligatorio sólo en autovía"], o_ru:["Обязателен всегда, и в городе тоже","Обязателен только за городом","Обязателен только на магистрали"], a:0,
 e:"Шлем на мотоцикле: обязателен всегда, и в городе тоже."},
{t:"seguridad", q:"¿Qué norma rige para la baliza V-16?", q_ru:"Какое правило действует для «маячок V-16»?",
 o:["Sustituye a los triángulos desde 2026","Se usa junto con los triángulos","Sólo es obligatoria de noche"], o_ru:["Заменяет треугольники с 2026 года","Используется вместе с треугольниками","Обязателен только ночью"], a:0,
 e:"Маячок v-16: заменяет треугольники с 2026 года."},
{t:"seguridad", q:"¿Qué norma rige para el chaleco reflectante?", q_ru:"Какое правило действует для «светоотражающий жилет»?",
 o:["Se pone antes de salir del coche","Se pone una vez fuera del coche","Sólo hace falta de noche"], o_ru:["Надевают до выхода из машины","Надевают уже снаружи","Нужен только ночью"], a:0,
 e:"Светоотражающий жилет: надевают до выхода из машины."},
{t:"seguridad", q:"¿Qué norma rige para la silla infantil hasta 135 cm?", q_ru:"Какое правило действует для «детское кресло до 135 см»?",
 o:["Obligatoria y en los asientos traseros","Obligatoria sólo en viajes largos","Basta con el cinturón del coche"], o_ru:["Обязательно, и на задних сиденьях","Обязательно только в дальних поездках","Хватает обычного ремня"], a:0,
 e:"Детское кресло до 135 см: обязательно, и на задних сиденьях."},
{t:"seguridad", q:"¿Qué norma rige para la silla a contramarcha delante?", q_ru:"Какое правило действует для «кресло против хода на переднем сиденье»?",
 o:["Exige desactivar el airbag frontal","Exige retrasar el asiento del todo","Está prohibida en cualquier caso"], o_ru:["Требует отключить подушку","Требует отодвинуть сиденье назад","Запрещено в любом случае"], a:0,
 e:"Кресло против хода на переднем сиденье: требует отключить подушку."},
{t:"seguridad", q:"¿Qué norma rige para el extintor en un turismo particular?", q_ru:"Какое правило действует для «огнетушитель в личной легковой»?",
 o:["No es obligatorio llevarlo","Es obligatorio desde hace años","Es obligatorio sólo en verano"], o_ru:["Возить необязательно","Обязателен уже много лет","Обязателен только летом"], a:0,
 e:"Огнетушитель в личной легковой: возить необязательно."},
{t:"seguridad", q:"¿Qué norma rige para la profundidad del dibujo del neumático?", q_ru:"Какое правило действует для «глубина протектора шины»?",
 o:["Mínimo un milímetro y seis","Mínimo dos milímetros y medio","Mínimo un milímetro justo"], o_ru:["Минимум полтора миллиметра с лишним","Минимум два с половиной миллиметра","Минимум ровно один миллиметр"], a:0,
 e:"Глубина протектора шины: минимум полтора миллиметра с лишним."},
{t:"seguridad", q:"¿Qué norma rige para la presión de los neumáticos?", q_ru:"Какое правило действует для «давление в шинах»?",
 o:["Se mide en frío, una vez al mes","Se mide en caliente tras rodar","Se mide una vez al año en la ITV"], o_ru:["Меряют на холодных, раз в месяц","Меряют на горячих после езды","Меряют раз в год на техосмотре"], a:0,
 e:"Давление в шинах: меряют на холодных, раз в месяц."},
{t:"seguridad", q:"¿Qué norma rige para los auriculares conectados al móvil?", q_ru:"Какое правило действует для «наушники, подключённые к телефону»?",
 o:["Están prohibidos al conducir","Se permiten fuera de ciudad","Se permiten con manos libres"], o_ru:["Запрещены за рулём","Разрешены за городом","Разрешены при свободных руках"], a:0,
 e:"Наушники, подключённые к телефону: запрещены за рулём."},
{t:"documentos", q:"¿Qué hay que saber sobre el permiso de conducir?", q_ru:"Что нужно знать про «водительские права»?",
 o:["Siempre encima al conducir","Sólo en los viajes largos","Basta una foto en el móvil"], o_ru:["Всегда с собой за рулём","Только в дальних поездках","Хватает фото в телефоне"], a:0,
 e:"Водительские права: всегда с собой за рулём."},
{t:"documentos", q:"¿Qué hay que saber sobre el permiso de circulación?", q_ru:"Что нужно знать про «свидетельство о регистрации»?",
 o:["Documento obligatorio del vehículo","Documento opcional, no siempre exigido","Sólo hace falta para vender el coche"], o_ru:["Обязательный документ на машину","Необязательный документ","Нужен только для продажи"], a:0,
 e:"Свидетельство о регистрации: обязательный документ на машину."},
{t:"documentos", q:"¿Qué hay que saber sobre la ficha técnica?", q_ru:"Что нужно знать про «техпаспорт с отметками ITV»?",
 o:["Documento obligatorio del vehículo","Sólo hace falta el día de la ITV","Sólo hace falta para vender el coche"], o_ru:["Обязательный документ на машину","Нужен только на техосмотре","Нужен только для продажи"], a:0,
 e:"Техпаспорт с отметками itv: обязательный документ на машину."},
{t:"documentos", q:"¿Qué hay que saber sobre el seguro obligatorio?", q_ru:"Что нужно знать про «обязательная страховка»?",
 o:["Cubre los daños a terceros","Cubre todos los daños propios","Cubre sólo al conductor"], o_ru:["Покрывает ущерб третьим лицам","Покрывает свой ущерб полностью","Покрывает только водителя"], a:0,
 e:"Обязательная страховка: покрывает ущерб третьим лицам."},
{t:"documentos", q:"¿Qué hay que saber sobre el distintivo ambiental?", q_ru:"Что нужно знать про «экологическая наклейка»?",
 o:["Clasifica el coche por emisiones","Clasifica el coche por antigüedad","Clasifica el coche por potencia"], o_ru:["Делит машины по выбросам","Делит машины по возрасту","Делит машины по мощности"], a:0,
 e:"Экологическая наклейка: делит машины по выбросам."},
{t:"documentos", q:"¿Qué hay que saber sobre la Zona de Bajas Emisiones?", q_ru:"Что нужно знать про «зона низких выбросов»?",
 o:["Obligatoria en ciudades grandes","Existe sólo en la capital","Funciona sólo los fines de semana"], o_ru:["Обязательна в крупных городах","Есть только в столице","Работает только по выходным"], a:0,
 e:"Зона низких выбросов: обязательна в крупных городах."},
];
if (typeof module !== "undefined") module.exports = PREGUNTAS_AUTO;
