/* Банк вопросов теста ПДД Испании.

   Поля:
     t     — тема: velocidad | senales | prioridad | alcohol | multas | seguridad | documentos
     q     — вопрос по-испански, как в зале экзамена
     q_ru  — перевод вопроса
     o     — варианты по-испански
     o_ru  — перевод вариантов, строка в строку
     a     — номер правильного (в банке всегда 0, порядок перемешивает движок)
     e     — короткое объяснение по-русски: почему так

   ⚠️ ЗАЧЕМ ПЕРЕВОД ВАРИАНТОВ. Без него тест бесполезен ровно тем, для кого сделан:
   человек понимает вопрос по переводу и упирается в три испанские строки, из которых
   надо выбрать. У французского сайта варианты короткие («130 km/h», «Vrai»), там это
   сходило с рук; по-испански варианты — целые фразы.

   ⚠️ ПРАВИЛЬНЫЙ ОТВЕТ В БАНКЕ ВСЕГДА ПЕРВЫЙ, и это не подсказка: движок перемешивает
   варианты честным Фишером-Йетсом и держит правильный за ТЕКСТ, а не за номер строки.
   Мерено: на 100 000 прогонов правильный попадает в каждую строку поровну.

   ⚠️ Правила сверены на сентябрь 2026. Две недавние перемены, которые надо
   перепроверять на dgt.es: 30 км/ч в городе (с мая 2021) и маячок V-16 вместо
   треугольников (обязателен с 1 января 2026).
*/
const PREGUNTAS = [

// ===== СКОРОСТЬ =====
{t:"velocidad", q:"En autopista o autovía, un turismo puede circular como máximo a:", q_ru:"По автомагистрали (autopista/autovía) легковой автомобиль может ехать максимум:",
 o:["120 km/h","130 km/h","110 km/h"], o_ru:["120 км/ч","130 км/ч","110 км/ч"], a:0,
 e:"120 — испанский потолок для легковых. 130 бывает во Франции, но не здесь."},
{t:"velocidad", q:"En carretera convencional, la velocidad máxima para turismos es:", q_ru:"На обычной загородной дороге (carretera convencional) максимум для легковых:",
 o:["90 km/h","100 km/h","80 km/h"], o_ru:["90 км/ч","100 км/ч","80 км/ч"], a:0,
 e:"С 2019 года на всех обычных дорогах 90, независимо от обочины."},
{t:"velocidad", q:"En una calle urbana de un solo carril por sentido, el límite general es:", q_ru:"На городской улице с одной полосой в каждую сторону общий лимит:",
 o:["30 km/h","50 km/h","40 km/h"], o_ru:["30 км/ч","50 км/ч","40 км/ч"], a:0,
 e:"Главная перемена мая 2021 года: большинство городских улиц теперь тридцатые."},
{t:"velocidad", q:"En vías urbanas de dos o más carriles por sentido, el límite general es:", q_ru:"На городских дорогах с двумя и более полосами в одну сторону лимит:",
 o:["50 km/h","30 km/h","60 km/h"], o_ru:["50 км/ч","30 км/ч","60 км/ч"], a:0,
 e:"Пятьдесят осталось только там, где полос в одну сторону две и больше."},
{t:"velocidad", q:"En calles de plataforma única (acera y calzada al mismo nivel), el límite es:", q_ru:"На улицах, где тротуар и проезжая часть на одном уровне, лимит:",
 o:["20 km/h","30 km/h","10 km/h"], o_ru:["20 км/ч","30 км/ч","10 км/ч"], a:0,
 e:"Единый уровень значит, что пешеход может шагнуть откуда угодно: двадцать."},
{t:"velocidad", q:"La velocidad mínima en autopista, salvo señalización, es:", q_ru:"Минимальная скорость на автомагистрали, если нет знака:",
 o:["60 km/h","40 km/h","80 km/h"], o_ru:["60 км/ч","40 км/ч","80 км/ч"], a:0,
 e:"Едущий медленнее 60 сам становится помехой — за это штрафуют."},
{t:"velocidad", q:"En España, ¿la lluvia reduce automáticamente el límite de velocidad?", q_ru:"Снижает ли дождь в Испании лимит скорости автоматически?",
 o:["No, pero hay que adecuar la velocidad","Sí, baja veinte kilómetros por hora","Sí, igual que en Francia y Portugal"], o_ru:["Нет, но скорость надо подстроить","Да, на двадцать километров в час меньше","Да, так же, как во Франции и Португалии"], a:0,
 e:"Испания не меняет цифру на знаке в дождь — в отличие от Франции. Но обязанность вести по условиям остаётся."},
{t:"velocidad", q:"Un turismo que arrastra un remolque ligero en autovía puede ir a:", q_ru:"Легковой с лёгким прицепом по автомагистрали может ехать:",
 o:["90 km/h","120 km/h","100 km/h"], o_ru:["90 км/ч","120 км/ч","100 км/ч"], a:0,
 e:"Прицеп сбивает лимит до девяноста даже на магистрали."},
{t:"velocidad", q:"En una zona residencial señalizada, la velocidad máxima es:", q_ru:"В обозначенной жилой зоне максимальная скорость:",
 o:["20 km/h","30 km/h","10 km/h"], o_ru:["20 км/ч","30 км/ч","10 км/ч"], a:0,
 e:"Жилая зона — двадцать, и пешеход там главнее машины."},
{t:"velocidad", q:"Para adelantar en carretera convencional, ¿puede superarse el límite?", q_ru:"Можно ли при обгоне на обычной дороге превысить лимит?",
 o:["No, ese margen ya no existe","Sí, hasta veinte por encima","Sí, hasta diez por encima"], o_ru:["Нет, такой поблажки больше нет","Да, до двадцати сверху","Да, до десяти сверху"], a:0,
 e:"Прежние 20 км/ч на обгон отменены: лимит есть лимит."},
{t:"velocidad", q:"El límite para autobuses en autopista es:", q_ru:"Лимит для автобусов на автомагистрали:",
 o:["100 km/h","120 km/h","90 km/h"], o_ru:["100 км/ч","120 км/ч","90 км/ч"], a:0,
 e:"Автобусу — сто, легковой машине — сто двадцать."},
{t:"velocidad", q:"En un tramo con velocidad recomendada (cuadro azul), circular más rápido:", q_ru:"На участке с рекомендованной скоростью (синий квадрат) ехать быстрее:",
 o:["Se permite si es seguro y no se supera el límite","Está prohibido siempre, aunque la vía esté vacía","Se multa siempre, incluso sin superar el límite"], o_ru:["Можно, если безопасно и лимит не превышен","Запрещено всегда, даже если дорога пуста","Штрафуют всегда, даже без превышения"], a:0,
 e:"Синий квадрат — совет, а не запрет. Запрещает круглый знак с красной каймой."},
{t:"velocidad", q:"Los radares de tramo miden:", q_ru:"Камеры «на участке» (radar de tramo) измеряют:",
 o:["La velocidad media entre dos puntos","La velocidad justo en un punto","Solo durante la noche"], o_ru:["Среднюю скорость между двумя точками","Скорость ровно в одной точке","Только ночью"], a:0,
 e:"Оттормозиться перед камерой не поможет: считают среднюю по всему отрезку."},
{t:"velocidad", q:"En vía urbana, superar el límite en más de 30 km/h supone:", q_ru:"В городе превышение более чем на 30 км/ч — это:",
 o:["Multa y pérdida de puntos","Solo un aviso del agente","Multa, pero sin puntos"], o_ru:["Штраф и снятие баллов","Только предупреждение","Штраф, но без баллов"], a:0,
 e:"Городское превышение на треть сотни уже стоит баллов, а не только денег."},
{t:"velocidad", q:"La velocidad debe reducirse obligatoriamente al aproximarse a:", q_ru:"Скорость обязательно снижают при приближении к:",
 o:["Un paso de peatones","Una gasolinera abierta","Un semáforo en verde"], o_ru:["Пешеходному переходу","Открытой заправке","Зелёному сигналу светофора"], a:0,
 e:"Перед переходом снижать обязан, даже если пешехода пока не видно."},
{t:"velocidad", q:"Los ciclomotores tienen prohibido circular por:", q_ru:"Мопедам запрещено движение по:",
 o:["Autopistas y autovías","Carreteras convencionales","Vías urbanas"], o_ru:["Автомагистралям обоих видов","Обычным загородным дорогам","Городским улицам"], a:0,
 e:"Мопед слишком медленный для магистрали — туда нельзя."},

// ===== ЗНАКИ =====
{t:"senales", q:"Las señales triangulares con borde rojo son de:", q_ru:"Треугольные знаки с красной каймой — это знаки:",
 o:["Advertencia de peligro","Obligación de hacer algo","Prohibición de hacer algo"], o_ru:["Предупреждения об опасности","Предписания что-то делать","Запрета что-то делать"], a:0,
 e:"Треугольник всегда предупреждает: дальше что-то опасное."},
{t:"senales", q:"Las señales circulares azules indican:", q_ru:"Круглые синие знаки означают:",
 o:["Obligación","Prohibición de circular","Advertencia de peligro"], o_ru:["Предписание","Запрет движения","Предупреждение об опасности"], a:0,
 e:"Синий круг приказывает: так ехать обязательно."},
{t:"senales", q:"Una señal circular con borde rojo indica normalmente:", q_ru:"Круглый знак с красной каймой обычно означает:",
 o:["Prohibición","Obligación","Información"], o_ru:["Запрет","Предписание","Информацию"], a:0,
 e:"Красная кайма по кругу — запрет. Синий круг — наоборот, предписание."},
{t:"senales", q:"La señal octogonal roja STOP obliga a:", q_ru:"Восьмиугольный красный STOP обязывает:",
 o:["Detenerse por completo antes de la línea","Reducir la velocidad y pasar con cuidado","Ceder el paso solo si se acerca alguien"], o_ru:["Полностью остановиться перед линией","Сбросить скорость и осторожно проехать","Уступить, только если кто-то приближается"], a:0,
 e:"STOP — остановка колёс, а не замедление. Пустой перекрёсток ничего не меняет."},
{t:"senales", q:"El triángulo invertido «Ceda el paso» significa:", q_ru:"Перевёрнутый треугольник «Ceda el paso» означает:",
 o:["Ceder el paso, sin detenerse obligatoriamente","Detenerse siempre por completo antes de la línea","Que la prioridad en ese cruce es siempre tuya"], o_ru:["Уступить, останавливаться необязательно","Всегда полностью останавливаться перед линией","Что приоритет на этом перекрёстке всегда твой"], a:0,
 e:"В этом и разница со STOP: тут можно не останавливаться, если дорога свободна."},
{t:"senales", q:"Una línea continua en el centro de la calzada:", q_ru:"Сплошная линия по центру проезжей части:",
 o:["No puede rebasarse ni pisarse","Puede rebasarse para adelantar","Solo sirve de orientación"], o_ru:["Её нельзя ни пересекать, ни наезжать","Её можно пересечь для обгона","Она только ориентир"], a:0,
 e:"Сплошную нельзя даже прижать колесом."},
{t:"senales", q:"Las señales cuadradas o rectangulares azules son de:", q_ru:"Квадратные и прямоугольные синие знаки — это:",
 o:["Indicación e información","Prohibición de circular","Advertencia de peligro"], o_ru:["Указание и информация","Запрет движения","Предупреждение об опасности"], a:0,
 e:"Форма решает: круг приказывает, квадрат подсказывает."},
{t:"senales", q:"La señal de calzada con prioridad (rombo amarillo) indica:", q_ru:"Знак «дорога с приоритетом» (жёлтый ромб) означает:",
 o:["Tienes prioridad en las intersecciones del tramo","Que debes ceder el paso en todos los cruces","Que la vía con prioridad termina aquí"], o_ru:["У тебя приоритет на перекрёстках участка","Что уступать нужно на всех перекрёстках","Что дорога с приоритетом здесь кончается"], a:0,
 e:"Жёлтый ромб — «главная дорога» до знака отмены."},
{t:"senales", q:"Una señal con fondo amarillo en obras significa:", q_ru:"Знак на жёлтом фоне в зоне работ означает:",
 o:["Prevalece sobre la señalización habitual","Que solo informa, sin obligar a nada","Que puede ignorarse si no hay obreros"], o_ru:["Он главнее постоянных знаков","Что он только сообщает, ни к чему не обязывая","Что его можно не выполнять, если нет рабочих"], a:0,
 e:"Жёлтый фон временный и перебивает обычную разметку и знаки."},
{t:"senales", q:"La marca amarilla en zigzag junto al bordillo indica:", q_ru:"Жёлтая зигзагообразная разметка у бордюра означает:",
 o:["Prohibido estacionar (parada o reserva)","Zona de carga y descarga de mercancías","Aparcamiento libre para los residentes"], o_ru:["Стоянка запрещена (остановка или резерв)","Зона погрузки и разгрузки товара","Свободная парковка для местных жителей"], a:0,
 e:"Зигзаг — обычно остановка автобуса или зарезервированное место."},
{t:"senales", q:"En caso de contradicción, ¿qué prevalece?", q_ru:"Если указания противоречат друг другу, что главнее?",
 o:["Las indicaciones del agente de tráfico","Las señales verticales de ese tramo","Las marcas viales pintadas en el suelo"], o_ru:["Указания регулировщика","Знаки на столбах этого участка","Разметка, нарисованная на асфальте"], a:0,
 e:"Порядок старшинства: регулировщик, светофор, знаки, разметка."},
{t:"senales", q:"Una señal circular blanca con borde rojo y nada dentro significa:", q_ru:"Круглый белый знак с красной каймой и пустой внутри означает:",
 o:["Circulación prohibida en ambos sentidos","Fin de todas las prohibiciones del tramo","Dirección obligatoria"], o_ru:["Движение запрещено в обе стороны","Конец всех запретов на участке","Обязательное направление"], a:0,
 e:"Пустой круг с красной каймой закрывает проезд обоим направлениям."},
{t:"senales", q:"El panel con una flecha blanca sobre fondo azul indica:", q_ru:"Синий знак с белой стрелкой означает:",
 o:["Sentido obligatorio","Sentido prohibido","Vía de servicio"], o_ru:["Обязательное направление","Запрещённое направление","Служебный проезд"], a:0,
 e:"Синий фон и стрелка — ехать только туда."},
{t:"senales", q:"Las señales de fin de prohibición suelen ser:", q_ru:"Знаки отмены запрета обычно:",
 o:["Circulares con banda oblicua","Triangulares con borde rojo","Cuadradas de color azul"], o_ru:["Круглые с косой полосой","Треугольные с красной каймой","Квадратные синие"], a:0,
 e:"Косая полоса по кругу — запрет снят."},
{t:"senales", q:"Una línea longitudinal discontinua permite:", q_ru:"Прерывистая продольная линия разрешает:",
 o:["Rebasarla para adelantar o cambiar de carril","Adelantar únicamente a bicicletas y motos","Nada: solo separa los carriles a la vista"], o_ru:["Пересекать её для обгона и смены полосы","Обгонять только велосипеды и мотоциклы","Ничего: она просто разделяет полосы на вид"], a:0,
 e:"Прерывистую пересекать можно, сплошную нельзя."},
{t:"senales", q:"El semáforo ámbar fijo obliga a:", q_ru:"Постоянный жёлтый сигнал светофора обязывает:",
 o:["Detenerse, salvo que frenar sea peligroso","Acelerar para pasar antes del rojo","Seguir adelante, el ámbar no obliga"], o_ru:["Остановиться, если торможение не опасно","Ускориться и проскочить до красного","Ехать дальше, жёлтый ни к чему не обязывает"], a:0,
 e:"Жёлтый — сигнал остановиться. Ехать можно, только если резкое торможение опаснее."},

// ===== ПРИОРИТЕТ =====
{t:"prioridad", q:"En una glorieta (rotonda), la prioridad la tienen:", q_ru:"На круговом (glorieta) приоритет у:",
 o:["Los vehículos que ya circulan por ella","Los vehículos que entran en ella","Los que circulan más rápido"], o_ru:["Тех, кто уже едет по кругу","Тех, кто въезжает","Тех, кто едет быстрее"], a:0,
 e:"Въезжающий уступает. Это обратное тому, к чему привыкли в некоторых странах."},
{t:"prioridad", q:"En un cruce sin señales ni semáforos, la prioridad es:", q_ru:"На перекрёстке без знаков и светофоров приоритет:",
 o:["Del que viene por la derecha","Del que circula en línea recta","Del vehículo más pesado"], o_ru:["У того, кто справа","У того, кто едет по прямой","У более тяжёлой машины"], a:0,
 e:"Помеха справа — правило по умолчанию, когда ничего не сказано."},
{t:"prioridad", q:"Al salir de un aparcamiento o vía privada:", q_ru:"При выезде с парковки или частной территории:",
 o:["Debes ceder el paso a todos","Tienes prioridad sobre la calle","Solo cedes a los peatones"], o_ru:["Уступаешь всем","У тебя приоритет над улицей","Уступаешь только пешеходам"], a:0,
 e:"Выезжающий всегда младше тех, кто уже на дороге."},
{t:"prioridad", q:"Un vehículo de emergencia con señales luminosas y acústicas:", q_ru:"Спецтранспорт с включёнными маячком и сиреной:",
 o:["Tiene prioridad y hay que facilitarle el paso","Tiene prioridad únicamente dentro de la ciudad","No tiene prioridad en las glorietas"], o_ru:["Имеет приоритет, ему освобождают дорогу","Имеет приоритет исключительно в городе","Не имеет приоритета на круговом"], a:0,
 e:"Маячок плюс сирена — приоритет везде, включая круговое."},
{t:"prioridad", q:"En un paso de peatones sin semáforo, el peatón:", q_ru:"На пешеходном переходе без светофора пешеход:",
 o:["Tiene prioridad","Debe esperar a que pase el coche","Tiene prioridad solo de día"], o_ru:["Имеет приоритет","Должен пропустить машину","Имеет приоритет только днём"], a:0,
 e:"На зебре без светофора пешеход главнее всегда."},
{t:"prioridad", q:"En una calle estrecha donde no caben dos vehículos:", q_ru:"На узкой улице, где двоим не разъехаться:",
 o:["Cede quien tenga la maniobra más fácil, según señalización","Cede siempre el que va cuesta abajo, sin excepción","Cede siempre el vehículo más pequeño de los dos"], o_ru:["Уступает тот, кому проще, по знакам","Всегда уступает едущий вниз, без исключений","Всегда уступает та машина, которая меньше"], a:0,
 e:"Смотрят на знак сужения, а если его нет — кому проще отступить."},
{t:"prioridad", q:"Los tranvías y vehículos sobre raíles:", q_ru:"Трамваи и рельсовый транспорт:",
 o:["Tienen prioridad sobre el resto","Ceden el paso en las glorietas","No tienen ninguna prioridad"], o_ru:["Имеют приоритет над остальными","Уступают на круговом","Не имеют приоритета"], a:0,
 e:"Рельсовый не может свернуть — поэтому идёт первым."},
{t:"prioridad", q:"Al girar a la derecha y cruzar un carril bici:", q_ru:"Поворачивая направо через велополосу:",
 o:["Debes ceder el paso a los ciclistas","Tienes prioridad por ir en coche","Basta con tocar el claxon"], o_ru:["Уступаешь велосипедистам","У тебя приоритет, ты на машине","Достаточно посигналить"], a:0,
 e:"Поворот пересекает чужую полосу — значит уступаешь."},
{t:"prioridad", q:"Al hacer un cambio de sentido, cedes el paso a:", q_ru:"При развороте уступаешь:",
 o:["Todos los vehículos, vengan de donde vengan","Solo a los que vienen por la izquierda","A nadie si hay hueco suficiente"], o_ru:["Всем машинам, откуда бы они ни ехали","Только тем, кто слева","Никому, если хватает промежутка"], a:0,
 e:"Разворот — манёвр с нуля приоритета: уступаешь обоим потокам."},
{t:"prioridad", q:"Un autobús urbano que sale de su parada señalizada:", q_ru:"Городской автобус, отъезжающий от обозначенной остановки:",
 o:["Tiene prioridad en vía urbana","No tiene ninguna prioridad","Tiene prioridad solo de día"], o_ru:["Имеет приоритет в городе","Не имеет приоритета","Имеет приоритет только днём"], a:0,
 e:"В городе автобусу от остановки уступают — редкое исключение в его пользу."},
{t:"prioridad", q:"En una intersección regulada por agente, sus señales:", q_ru:"На перекрёстке с регулировщиком его сигналы:",
 o:["Prevalecen sobre semáforos y señales","Valen menos que el semáforo del cruce","Son solo recomendaciones para el tráfico"], o_ru:["Главнее светофора и знаков","Слабее, чем светофор на перекрёстке","Это просто советы для потока машин"], a:0,
 e:"Регулировщик старше всех, даже красного света."},
{t:"prioridad", q:"Al incorporarte a una autovía por el carril de aceleración:", q_ru:"При выезде на автомагистраль по полосе разгона:",
 o:["Debes ceder el paso a los que ya circulan","Tienes prioridad por venir acelerando","Debes frenar al final del carril"], o_ru:["Уступаешь тем, кто уже едет","У тебя приоритет, ты разгоняешься","Надо тормозить в конце полосы"], a:0,
 e:"Полоса разгона нужна, чтобы влиться на скорости потока, а не чтобы влезть."},
{t:"prioridad", q:"Un ciclista dentro de una glorieta:", q_ru:"Велосипедист внутри кругового:",
 o:["Tiene prioridad como cualquier vehículo dentro","Debe ceder el paso a los coches que entran","No puede entrar en la glorieta por ley"], o_ru:["Имеет приоритет, как любой внутри","Должен уступать машинам, которые въезжают","Не имеет права въезжать туда по закону"], a:0,
 e:"Внутри круга велосипед — такой же участник, как машина."},
{t:"prioridad", q:"Los peatones en una zona peatonal o residencial:", q_ru:"Пешеходы в пешеходной или жилой зоне:",
 o:["Tienen prioridad sobre los vehículos","Deben ceder el paso a los coches","Solo pueden cruzar por los pasos"], o_ru:["Имеют приоритет над машинами","Должны уступать машинам","Могут переходить только по зебре"], a:0,
 e:"В таких зонах машина — гость, а не хозяин."},
{t:"prioridad", q:"Si un semáforo está apagado o en ámbar intermitente, rige:", q_ru:"Если светофор погас или мигает жёлтым, действуют:",
 o:["La señalización vertical o la prioridad de la derecha","Nada en absoluto: pasa el primero que llegue al cruce","Siempre tiene el paso el que viene de frente"], o_ru:["Знаки или помеха справа","Совсем ничего: кто первый подъехал, тот и прав","Всегда проезжает встречный"], a:0,
 e:"Выключенный светофор возвращает перекрёсток к знакам, а если их нет — к помехе справа."},

// ===== АЛКОГОЛЬ И ЛЕКАРСТВА =====
{t:"alcohol", q:"La tasa general máxima de alcohol en aire espirado es:", q_ru:"Общий максимум алкоголя в выдыхаемом воздухе:",
 o:["0,25 mg/l","0,30 mg/l","0,15 mg/l"], o_ru:["0,25 мг/л","0,30 мг/л","0,15 мг/л"], a:0,
 e:"Цифру спрашивают часто: 0,25 в воздухе — общая норма."},
{t:"alcohol", q:"La tasa general máxima de alcohol en sangre es:", q_ru:"Общий максимум алкоголя в крови:",
 o:["0,5 g/l","0,8 g/l","0,3 g/l"], o_ru:["0,5 г/л","0,8 г/л","0,3 г/л"], a:0,
 e:"Пара к предыдущей: 0,5 в крови соответствует 0,25 в воздухе."},
{t:"alcohol", q:"Para conductores noveles y profesionales, la tasa en aire es:", q_ru:"Для новичков и профессионалов норма в выдыхаемом воздухе:",
 o:["0,15 mg/l","0,25 mg/l","0,30 mg/l"], o_ru:["0,15 мг/л","0,25 мг/л","0,30 мг/л"], a:0,
 e:"Новичку и профессионалу нормы урезаны почти вдвое."},
{t:"alcohol", q:"La presencia de drogas en el organismo del conductor:", q_ru:"Наличие наркотиков в организме водителя:",
 o:["Está prohibida, con tolerancia cero","Se tolera en pequeña cantidad","Se sanciona solo si hay accidente"], o_ru:["Запрещено, нулевая терпимость","Допустимо в малом количестве","Наказывают только при аварии"], a:0,
 e:"С наркотиками порога нет вовсе: наказывает сам факт присутствия."},
{t:"alcohol", q:"Negarse a las pruebas de alcoholemia es:", q_ru:"Отказ от проверки на алкоголь — это:",
 o:["Un delito penal","Una falta leve","Algo sin consecuencias"], o_ru:["Уголовное преступление","Мелкое нарушение","Ничего не значит"], a:0,
 e:"Отказ наказывается строже, чем сам положительный тест."},
{t:"alcohol", q:"Conducir con 0,60 mg/l en aire espirado es:", q_ru:"Управление с показателем 0,60 мг/л в воздухе — это:",
 o:["Delito contra la seguridad vial","Una infracción leve","Una infracción administrativa sin más"], o_ru:["Преступление против безопасности движения","Лёгкое нарушение","Обычное административное нарушение"], a:0,
 e:"Выше 0,60 в воздухе начинается уголовная статья, а не штраф."},
{t:"alcohol", q:"El alcohol, sobre el conductor, produce:", q_ru:"Алкоголь на водителя действует так:",
 o:["Aumenta el tiempo de reacción y da falsa seguridad","Mejora los reflejos y la atención al volante","Solo afecta un poco a la visión periférica"], o_ru:["Удлиняет реакцию и даёт ложную уверенность","Улучшает реакцию и внимание за рулём","Немного влияет только на боковое зрение"], a:0,
 e:"Опаснее всего именно ложная уверенность: человек считает, что ведёт лучше."},
{t:"alcohol", q:"El café o una ducha fría tras beber:", q_ru:"Кофе или холодный душ после выпитого:",
 o:["No reducen la tasa de alcohol","Reducen la tasa a la mitad","Eliminan el alcohol del cuerpo"], o_ru:["Не снижают уровень алкоголя","Снижают его вдвое","Полностью выводят алкоголь"], a:0,
 e:"Бодрость возвращается, промилле — нет. Выводит только время."},
{t:"alcohol", q:"Los medicamentos que producen somnolencia se señalan con:", q_ru:"Лекарства, вызывающие сонливость, помечают:",
 o:["Un pictograma de conducción en la caja","Ninguna marca especial en el envase","Una etiqueta de color verde en el envase"], o_ru:["Значком с машиной на упаковке","Ничем особенным на упаковке","Зелёной наклейкой на упаковке"], a:0,
 e:"Значок с машиной на коробке — предупреждение, что за руль нельзя."},
{t:"alcohol", q:"El control de alcoholemia puede hacerse:", q_ru:"Проверку на алкоголь могут провести:",
 o:["En cualquier control preventivo, sin infracción previa","Solo después de un accidente de tráfico, nunca antes","Solo si alguien ha presentado una denuncia"], o_ru:["На любой профилактической проверке, без нарушения","Только после дорожной аварии, и никогда раньше","Только если кто-то подал жалобу"], a:0,
 e:"Для проверки не нужен повод: достаточно самой проверки."},
{t:"alcohol", q:"Superar la tasa permitida de alcohol resta:", q_ru:"Превышение допустимой нормы алкоголя отнимает:",
 o:["4 o 6 puntos según la tasa","Un solo punto","Ningún punto, solo multa"], o_ru:["4 или 6 баллов, смотря сколько","Один балл","Ни одного, только штраф"], a:0,
 e:"Чем выше показатель, тем больше баллов: четыре или шесть."},
{t:"alcohol", q:"La eliminación del alcohol en el cuerpo depende sobre todo de:", q_ru:"Вывод алкоголя из организма зависит прежде всего от:",
 o:["El tiempo transcurrido","La comida ingerida","El ejercicio físico"], o_ru:["Прошедшего времени","Съеденного","Физической нагрузки"], a:0,
 e:"Ни еда, ни спорт не ускоряют печень заметно."},
{t:"alcohol", q:"Dar positivo en drogas al volante supone:", q_ru:"Положительный тест на наркотики за рулём означает:",
 o:["Multa elevada y pérdida de puntos","Solo una advertencia verbal","Una multa pequeña de doscientos euros"], o_ru:["Крупный штраф и снятие баллов","Только устное предупреждение","Небольшой штраф в двести евро"], a:0,
 e:"Наказание сопоставимо с крепким алкоголем: деньги плюс баллы."},
{t:"alcohol", q:"Tras una noche de fiesta, por la mañana:", q_ru:"После ночной вечеринки утром:",
 o:["Aún puede haber alcohol en sangre","El cuerpo siempre está limpio","Basta con dormir dos horas"], o_ru:["Алкоголь ещё может быть в крови","Организм всегда чист","Достаточно поспать два часа"], a:0,
 e:"Утренние проверки ловят именно вчерашних: печень работает медленно."},

// ===== ШТРАФЫ И БАЛЛЫ =====
{t:"multas", q:"Un conductor con permiso ordinario dispone inicialmente de:", q_ru:"У обычного водителя изначально баллов:",
 o:["12 puntos","15 puntos","8 puntos"], o_ru:["12 баллов","15 баллов","8 баллов"], a:0,
 e:"Двенадцать — стартовый баланс обычного водителя."},
{t:"multas", q:"Un conductor novel dispone de:", q_ru:"У начинающего водителя баллов:",
 o:["8 puntos","12 puntos","6 puntos"], o_ru:["8 баллов","12 баллов","6 баллов"], a:0,
 e:"Новичку дают восемь: запас меньше, цена ошибки выше."},
{t:"multas", q:"Tras tres años sin perder puntos, el saldo puede llegar a:", q_ru:"После трёх лет без потерь баланс может вырасти до:",
 o:["15 puntos","12 puntos","20 puntos"], o_ru:["15 баллов","12 баллов","20 баллов"], a:0,
 e:"Пятнадцать — потолок, награда за спокойную езду."},
{t:"multas", q:"Usar el teléfono móvil en la mano conduciendo resta:", q_ru:"Телефон в руке за рулём отнимает:",
 o:["6 puntos","3 puntos","1 punto"], o_ru:["6 баллов","3 балла","1 балл"], a:0,
 e:"С 2022 года телефон в руке стоит шести баллов — как алкоголь."},
{t:"multas", q:"No usar el cinturón de seguridad resta:", q_ru:"Непристёгнутый ремень отнимает:",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"Ремень — четыре балла, столько же, сколько красный свет."},
{t:"multas", q:"Una multa pagada en los 20 días naturales tiene descuento del:", q_ru:"Штраф при оплате в течение 20 дней даёт скидку:",
 o:["50 %","30 %","20 %"], o_ru:["50 %","30 %","20 %"], a:0,
 e:"Половина цены — но оплата означает согласие: обжаловать потом нельзя."},
{t:"multas", q:"Al quedarse sin puntos, el conductor:", q_ru:"Оставшись без баллов, водитель:",
 o:["Pierde la vigencia del permiso y lo recupera con cursos","Paga una multa mayor y sigue conduciendo igual","Espera un año natural y sigue conduciendo"], o_ru:["Теряет силу прав и возвращает их курсами","Платит штраф побольше и едет дальше как ни в чём","Ждёт ровно год, и всё возвращается само"], a:0,
 e:"Права не отбирают навсегда, но вернуть их можно только через курсы и экзамен."},
{t:"multas", q:"Las multas pueden notificarse electrónicamente a través de:", q_ru:"Штрафы могут приходить электронно через:",
 o:["La Dirección Electrónica Vial (DEV)","Un SMS obligatorio al móvil","Solo correo certificado en papel"], o_ru:["Электронный адрес DEV","Обязательную SMS на телефон","Только бумажное заказное письмо"], a:0,
 e:"DEV — электронный почтовый ящик водителя: письмо туда считается врученным."},
{t:"multas", q:"Conducir sin seguro obligatorio supone:", q_ru:"Езда без обязательной страховки — это:",
 o:["Multa elevada e inmovilización del vehículo","Una simple advertencia verbal del agente","Una multa pequeña de ochenta euros"], o_ru:["Крупный штраф и задержание машины","Простое устное предупреждение","Небольшой штраф в восемьдесят евро"], a:0,
 e:"Машину без страховки могут увезти на штрафстоянку прямо с места."},
{t:"multas", q:"Arrojar a la vía objetos que puedan provocar incendio resta:", q_ru:"Выброс на дорогу предметов, способных вызвать пожар, отнимает:",
 o:["6 puntos","4 puntos","2 puntos"], o_ru:["6 баллов","4 балла","2 балла"], a:0,
 e:"Окурок в окно в сухой сезон — шесть баллов: Испания горит каждое лето."},
{t:"multas", q:"El plazo general para recurrir una multa es de:", q_ru:"Общий срок обжалования штрафа:",
 o:["20 días naturales","10 días naturales","3 meses"], o_ru:["20 календарных дней","10 календарных дней","3 месяца"], a:0,
 e:"Те же двадцать дней, что и на скидку: или платишь вдвое дешевле, или споришь."},
{t:"multas", q:"Circular por el arcén sin causa justificada es:", q_ru:"Езда по обочине без причины — это:",
 o:["Una infracción sancionable","Algo permitido si hay atasco","Algo permitido durante el día"], o_ru:["Наказуемое нарушение","Можно, если пробка","Можно в светлое время"], a:0,
 e:"Обочина не полоса: по ней едут только при вынужденной остановке."},
{t:"multas", q:"No respetar un semáforo en rojo resta:", q_ru:"Проезд на красный отнимает:",
 o:["4 puntos","2 puntos","6 puntos"], o_ru:["4 балла","2 балла","6 баллов"], a:0,
 e:"Красный — четыре балла. Шесть стоят телефон, алкоголь и окурок."},
{t:"multas", q:"Para recuperar el saldo total de puntos hay que:", q_ru:"Чтобы вернуть полный баланс баллов, нужно:",
 o:["Pasar dos años sin infracciones graves","Pagar una tasa administrativa en la Jefatura","Esperar seis meses sin conducir"], o_ru:["Два года без серьёзных нарушений","Заплатить административную пошлину в Jefatura","Полгода не садиться за руль"], a:0,
 e:"Баланс восстанавливается временем, а не деньгами."},

// ===== БЕЗОПАСНОСТЬ И ТЕХНИКА =====
{t:"seguridad", q:"Desde el 1 de enero de 2026, en caso de avería hay que señalizar con:", q_ru:"С 1 января 2026 года при поломке обозначаться нужно:",
 o:["La baliza luminosa V-16 conectada","Los dos triángulos de siempre","Un triángulo y el chaleco"], o_ru:["Светящимся маячком V-16 с подключением","Двумя привычными треугольниками","Треугольником и жилетом"], a:0,
 e:"Треугольники отменены: маячок сам сообщает о месте в систему DGT."},
{t:"seguridad", q:"La baliza V-16 se coloca:", q_ru:"Маячок V-16 ставится:",
 o:["En el punto más alto del vehículo, sin bajar a la calzada","A cincuenta metros por detrás, en la calzada","Dentro del coche, sobre el salpicadero delantero"], o_ru:["На самой высокой точке машины, не выходя на дорогу","В пятидесяти метрах позади, на проезжей части","Внутри машины, на передней панели"], a:0,
 e:"Смысл перемены в том, чтобы человек не шёл по обочине с треугольником."},
{t:"seguridad", q:"El chaleco reflectante debe ponerse:", q_ru:"Светоотражающий жилет надевают:",
 o:["Antes de salir del vehículo a la calzada","Solo cuando ya es de noche cerrada","Solo en autopista, autovía y túneles"], o_ru:["До того как выйти из машины на дорогу","Только когда уже совсем стемнело","Только на автомагистрали и в туннелях"], a:0,
 e:"Жилет надевают внутри машины — иначе он бесполезен."},
{t:"seguridad", q:"Los niños de menos de 135 cm deben viajar:", q_ru:"Дети ростом менее 135 см должны ехать:",
 o:["En los asientos traseros con sistema de retención","Delante, sujetos con el cinturón del coche","En cualquier plaza del coche, según prefieran"], o_ru:["Сзади, в удерживающем устройстве","Впереди, пристёгнутыми обычным ремнём","На любом месте машины, как им удобнее"], a:0,
 e:"Рост, а не возраст, решает: планка — 135 сантиметров."},
{t:"seguridad", q:"La ITV de un turismo particular de 4 a 10 años se pasa:", q_ru:"Техосмотр (ITV) легкового 4-10 лет проходят:",
 o:["Cada dos años","Cada año","Cada cuatro años"], o_ru:["Раз в два года","Ежегодно","Раз в четыре года"], a:0,
 e:"До четырёх лет ITV не нужен, после десяти — уже ежегодно."},
{t:"seguridad", q:"La profundidad mínima legal del dibujo de los neumáticos es:", q_ru:"Минимальная законная глубина протектора шин:",
 o:["1,6 mm","2,5 mm","1,0 mm"], o_ru:["1,6 мм","2,5 мм","1,0 мм"], a:0,
 e:"Ниже 1,6 мм шина не отводит воду — и начинается аквапланирование."},
{t:"seguridad", q:"El casco es obligatorio para motoristas:", q_ru:"Шлем для мотоциклистов обязателен:",
 o:["Siempre, también dentro de la ciudad","Solo fuera de la ciudad, en carretera","Solo en autovía y autopista"], o_ru:["Всегда, в том числе в городе","Только за городом, на трассе","Только на автомагистрали и в туннелях"], a:0,
 e:"Исключений по городу нет."},
{t:"seguridad", q:"Con niebla densa deben encenderse:", q_ru:"В густом тумане включают:",
 o:["Las luces de niebla y la de cruce","Las luces largas de carretera","Solo las luces de posición"], o_ru:["Противотуманные и ближний свет","Дальний свет","Только габариты"], a:0,
 e:"Дальний в тумане слепит самого водителя: свет отражается от капель."},
{t:"seguridad", q:"Las luces de carretera (largas) deben apagarse:", q_ru:"Дальний свет выключают:",
 o:["Al cruzarse con otro vehículo o seguirlo de cerca","Nunca, mientras la carretera esté vacía","Solo dentro de la ciudad y en los túneles"], o_ru:["При встрече со встречным и при езде вплотную","Никогда, пока дорога впереди пуста","Только в городе и в туннелях"], a:0,
 e:"Ослеплённый встречный — авария через секунду."},
{t:"seguridad", q:"La distancia de seguridad debe permitir:", q_ru:"Дистанция безопасности должна позволять:",
 o:["Detenerse sin colisionar ante una frenada brusca","Adelantar con rapidez al coche de delante","Leer la matrícula del coche anterior"], o_ru:["Остановиться без удара при резком торможении","Быстро обогнать машину впереди","Прочитать номер передней машины"], a:0,
 e:"Мера дистанции — тормозной путь, а не глазомер."},
{t:"seguridad", q:"El cinturón de seguridad es obligatorio:", q_ru:"Ремень безопасности обязателен:",
 o:["En todas las plazas, delante y detrás","Solo en los asientos delanteros","Solo fuera de la ciudad, en carretera"], o_ru:["На всех местах, спереди и сзади","Только на передних сиденьях","Только за городом, на трассе"], a:0,
 e:"Задний непристёгнутый в аварии летит вперёд и убивает переднего."},
{t:"seguridad", q:"El aquaplaning se produce cuando:", q_ru:"Аквапланирование возникает, когда:",
 o:["Una capa de agua separa el neumático del asfalto","El motor se calienta por encima de lo normal","Se frena en seco sobre asfalto seco"], o_ru:["Слой воды отделяет шину от асфальта","Двигатель перегревается","Резко тормозишь на сухом асфальте"], a:0,
 e:"Колесо всплывает: руль и тормоз перестают действовать."},
{t:"seguridad", q:"Ante un reventón de neumático en marcha hay que:", q_ru:"При разрыве шины на ходу нужно:",
 o:["Sujetar firme el volante y frenar suave","Frenar a fondo de inmediato y parar","Girar rápido hacia el arcén derecho"], o_ru:["Крепко держать руль и тормозить плавно","Немедленно тормозить в пол и встать","Резко свернуть на правую обочину"], a:0,
 e:"Резкое движение при разрыве разворачивает машину поперёк."},
{t:"seguridad", q:"La presión de los neumáticos se comprueba:", q_ru:"Давление в шинах проверяют:",
 o:["En frío y al menos una vez al mes","En caliente, después de conducir","Una vez al año, en la ITV"], o_ru:["На холодных шинах, раз в месяц","На горячих, после поездки","Раз в год, на техосмотре"], a:0,
 e:"Горячая шина показывает завышенное давление — замер врёт."},
{t:"seguridad", q:"Hablar por teléfono con cascos o auriculares conduciendo:", q_ru:"Разговор по телефону в наушниках за рулём:",
 o:["Está prohibido","Está permitido sin límites","Se permite dentro de la ciudad"], o_ru:["Запрещено","Разрешено без ограничений","Разрешено в городе"], a:0,
 e:"Наушники отрезают звуки дороги — запрещены, даже свободные руки."},
{t:"seguridad", q:"La somnolencia al volante se combate:", q_ru:"С сонливостью за рулём борются:",
 o:["Parando a descansar","Subiendo el volumen de la música","Abriendo la ventanilla y siguiendo"], o_ru:["Остановкой и отдыхом","Громкой музыкой","Открытым окном и ездой дальше"], a:0,
 e:"Музыка и окно дают несколько минут — и микросон приходит всё равно."},

// ===== ДОКУМЕНТЫ И ЭКЗАМЕН =====
{t:"documentos", q:"El examen teórico de la DGT consta de:", q_ru:"Теоретический экзамен DGT состоит из:",
 o:["30 preguntas, con 3 fallos como máximo","40 preguntas, con 5 fallos como máximo","20 preguntas, con 2 fallos como máximo"], o_ru:["30 вопросов, максимум 3 ошибки","40 вопросов, максимум 5 ошибок","20 вопросов, максимум 2 ошибки"], a:0,
 e:"Тридцать вопросов и три ошибки — по этому счёту считает и наш тест."},
{t:"documentos", q:"El organismo que gestiona permisos y exámenes en España es:", q_ru:"Права и экзамены в Испании ведёт:",
 o:["La DGT (Dirección General de Tráfico)","El ayuntamiento de cada ciudad o pueblo","La Seguridad Social"], o_ru:["DGT — управление дорожного движения","Мэрия каждого города или посёлка","Служба соцстрахования"], a:0,
 e:"DGT — единственное ведомство по правам на всю страну."},
{t:"documentos", q:"El expediente del permiso se lleva en:", q_ru:"Личное дело по правам ведёт:",
 o:["La Jefatura Provincial de Tráfico","La comisaría de policía del barrio","El consulado del país de origen"], o_ru:["Провинциальное управление Tráfico","Районный полицейский участок","Консульство своей страны"], a:0,
 e:"Все вопросы по делу — в свою Jefatura, а не в общий колл-центр."},
{t:"documentos", q:"El canje de un permiso extranjero es posible:", q_ru:"Обмен иностранных прав (canje) возможен:",
 o:["Solo con países que tienen acuerdo con España","Con cualquier país del mundo, sin excepción","Solo con países de la Unión Europea"], o_ru:["Только со странами, у которых есть соглашение","С любой страной мира, без исключений","Только со странами Евросоюза"], a:0,
 e:"Список стран-участниц — на dgt.es. Это единственное место, где он верен."},
{t:"documentos", q:"Documentación obligatoria del vehículo:", q_ru:"Обязательные документы на автомобиль:",
 o:["Permiso de circulación, ficha técnica y seguro","Solo el seguro obligatorio del vehículo","Solo la ficha técnica del vehículo"], o_ru:["Свидетельство, техпаспорт и страховка","Только обязательная страховка на машину","Только техпаспорт"], a:0,
 e:"Три бумаги, и возить надо все три."},
{t:"documentos", q:"El permiso B permite conducir turismos con masa máxima de hasta:", q_ru:"Категория B разрешает автомобили с максимальной массой до:",
 o:["3.500 kg","5.000 kg","2.500 kg"], o_ru:["3500 кг","5000 кг","2500 кг"], a:0,
 e:"Три с половиной тонны — общеевропейская граница категории B."},
{t:"documentos", q:"El permiso B se obtiene a partir de los:", q_ru:"Категорию B можно получить с:",
 o:["18 años","16 años","21 años"], o_ru:["18 лет","16 лет","21 года"], a:0,
 e:"С шестнадцати можно только мопед и лёгкий мотоцикл."},
{t:"documentos", q:"Tras aprobar el teórico, el práctico debe hacerse dentro de:", q_ru:"После сдачи теории практику нужно сдать в течение:",
 o:["Dos años de validez del teórico","Seis meses desde el aprobado","Un mes desde el aprobado"], o_ru:["Двух лет — столько годна теория","Полугода после сдачи","Месяца после сдачи"], a:0,
 e:"Два года — запас приличный, но он кончается, и теорию сдают заново."},
{t:"documentos", q:"La L de conductor novel debe llevarse:", q_ru:"Знак L (новичок) нужно возить:",
 o:["El primer año, visible en la parte trasera","Durante los tres primeros años de permiso","No es obligatoria en ningún caso"], o_ru:["Первый год, на виду сзади","Первые три года после получения прав","Она вообще не обязательна"], a:0,
 e:"Год с буквой L — и только год."},
{t:"documentos", q:"¿Tiene el conductor novel un límite de velocidad especial?", q_ru:"Есть ли у начинающего водителя особый лимит скорости?",
 o:["No, ese límite ya no existe","Sí, ochenta por hora en carretera","Sí, cien por hora en autovía"], o_ru:["Нет, такого лимита больше нет","Да, восемьдесят в час на трассе","Да, сто в час на магистрали"], a:0,
 e:"Ограничение для новичков отменили давно — в отличие от Франции, где оно есть."},
{t:"documentos", q:"La renovación del permiso B para menores de 65 años es cada:", q_ru:"Продление категории B для тех, кому меньше 65, — каждые:",
 o:["10 años","5 años","15 años"], o_ru:["10 лет","5 лет","15 лет"], a:0,
 e:"После 65 срок сокращается до пяти лет."},
{t:"documentos", q:"Para renovar el permiso hace falta:", q_ru:"Для продления прав нужно:",
 o:["Un informe de aptitud psicofísica de un centro autorizado","Solo pagar la tasa correspondiente en el banco","Aprobar otra vez el teórico y también el práctico"], o_ru:["Справка о годности из лицензированного центра","Только оплатить пошлину в банке","Снова сдать и теорию, и практику"], a:0,
 e:"Медцентр (centro de reconocimiento) сам отправляет справку в DGT."},
{t:"documentos", q:"Conducir sin haber obtenido nunca el permiso es:", q_ru:"Езда без когда-либо полученных прав — это:",
 o:["Un delito penal","Una infracción leve","Una multa de doscientos euros"], o_ru:["Уголовное преступление","Лёгкое нарушение","Штраф в двести евро"], a:0,
 e:"Никогда не имевший прав отвечает по уголовной статье, а не по административной."},
{t:"documentos", q:"El permiso de conducir debe llevarse:", q_ru:"Права нужно возить:",
 o:["Siempre encima al conducir","Solo en los viajes largos","Basta con una foto en el móvil"], o_ru:["Всегда с собой за рулём","Только в дальних поездках","Достаточно фото в телефоне"], a:0,
 e:"Фотография в телефоне документом не считается."},

// ===== ДОБАВЛЕНО 16 сентября 2026 =====
// ⚠️ Варианты писались сразу сопоставимой длины: аудит ловит, когда правильный
// длиннее прочих в 1,2 раза — такой тест сдаётся угадыванием, без знания правил.

// --- скорость ---
{t:"velocidad", q:"La velocidad máxima de un ciclomotor, por construcción, es:", q_ru:"Максимальная скорость мопеда по конструкции:",
 o:["45 km/h","50 km/h","40 km/h"], o_ru:["45 км/ч","50 км/ч","40 км/ч"], a:0,
 e:"Мопед — это до 45 км/ч и до 50 кубиков. Быстрее — уже мотоцикл, и права другие."},
{t:"velocidad", q:"Un camión de más de 3.500 kg en autopista puede circular a:", q_ru:"Грузовик тяжелее 3500 кг по автомагистрали может ехать:",
 o:["90 km/h","100 km/h","80 km/h"], o_ru:["90 км/ч","100 км/ч","80 км/ч"], a:0,
 e:"Грузовику — девяносто, автобусу — сто, легковой — сто двадцать."},
{t:"velocidad", q:"Una motocicleta en autopista tiene como límite:", q_ru:"Мотоцикл на автомагистрали ограничен скоростью:",
 o:["120 km/h","100 km/h","110 km/h"], o_ru:["120 км/ч","100 км/ч","110 км/ч"], a:0,
 e:"У мотоцикла тот же потолок, что у легковой машины."},
{t:"velocidad", q:"En una travesía, el límite que se aplica es el de:", q_ru:"На участке дороги, проходящем через посёлок (travesía), действует лимит:",
 o:["Vía urbana, aunque sea carretera","Carretera convencional siempre","Autovía, si la vía es ancha"], o_ru:["Городской улицы, хоть это и трасса","Обычной загородной дороги","Магистрали, если дорога широкая"], a:0,
 e:"Дорога проходит через посёлок — значит считается городской, со всеми городскими лимитами."},
{t:"velocidad", q:"Al adelantar a un ciclista hay que dejar una separación de:", q_ru:"При обгоне велосипедиста нужно оставить зазор:",
 o:["Un metro y medio como mínimo","Un metro es suficiente","Medio metro basta en ciudad"], o_ru:["Минимум полтора метра","Хватает одного метра","В городе хватает полуметра"], a:0,
 e:"Полтора метра — и ради них разрешено пересечь сплошную, если встречная свободна."},
{t:"velocidad", q:"Los ciclistas mayores de 14 años en autovía pueden circular:", q_ru:"Велосипедисты старше 14 лет по автомагистрали (autovía) могут ехать:",
 o:["Por el arcén, salvo prohibición expresa","Por el carril derecho sin límites","No pueden circular en ningún caso"], o_ru:["По обочине, если нет прямого запрета","По правой полосе без ограничений","Не могут вообще ни при каких условиях"], a:0,
 e:"По autovía — только по обочине и только с 14 лет. По autopista нельзя совсем."},
{t:"velocidad", q:"En un aparcamiento o zona peatonal, la velocidad máxima es:", q_ru:"На парковке или в пешеходной зоне максимальная скорость:",
 o:["20 km/h","30 km/h","10 km/h"], o_ru:["20 км/ч","30 км/ч","10 км/ч"], a:0,
 e:"Там, где ходят люди без тротуара, — двадцать."},
{t:"velocidad", q:"Circular muy por debajo del límite sin causa justificada:", q_ru:"Езда сильно медленнее лимита без причины:",
 o:["Es sancionable si entorpece la circulación","Nunca se sanciona, es incluso más seguro","Solo se sanciona en autopista"], o_ru:["Наказуема, если мешает движению","Не наказуема никогда, так даже безопаснее","Наказуема только на магистрали и автовии"], a:0,
 e:"Слишком медленный водитель — такая же помеха, как слишком быстрый."},

// --- знаки ---
{t:"senales", q:"Una señal cuadrada azul con una P blanca indica:", q_ru:"Синий квадратный знак с белой буквой P означает:",
 o:["Estacionamiento permitido","Prohibido estacionar ahí","Parada de autobús urbano"], o_ru:["Стоянка разрешена","Стоянка запрещена","Остановка городского автобуса"], a:0,
 e:"Синий квадрат сообщает, а не запрещает: здесь можно стоять."},
{t:"senales", q:"Una doble línea continua en el centro de la calzada:", q_ru:"Двойная сплошная по центру проезжей части:",
 o:["No puede rebasarse en ningún sentido","Puede rebasarla quien va adelantando","Solo separa los sentidos, sin prohibir"], o_ru:["Нельзя пересекать ни в одну сторону","Её может пересечь тот, кто обгоняет","Просто разделяет потоки, ничего не запрещая"], a:0,
 e:"Двойная сплошная закрывает обгон обоим направлениям."},
{t:"senales", q:"El triángulo con un signo de exclamación advierte de:", q_ru:"Треугольник с восклицательным знаком предупреждает о:",
 o:["Un peligro no recogido en otras señales","Una zona de obras permanente","Un cruce con prioridad a la derecha"], o_ru:["Опасности, для которой нет своего знака","Постоянной зоне ремонта","Перекрёстке с помехой справа"], a:0,
 e:"Это «прочие опасности»: подробности пишут на табличке под знаком."},
{t:"senales", q:"La luz amarilla intermitente de un semáforo significa:", q_ru:"Мигающий жёлтый сигнал светофора означает:",
 o:["Pasar con precaución, rige la señalización","Detenerse por completo y esperar","Que el semáforo está averiado y no rige"], o_ru:["Ехать осторожно, действуют знаки","Полностью остановиться и ждать","Что светофор сломан и не действует"], a:0,
 e:"Мигающий жёлтый возвращает перекрёсток к знакам, а если их нет — к помехе справа."},
{t:"senales", q:"Un círculo rojo con dos coches, uno rojo y otro negro, prohíbe:", q_ru:"Круг с красной каймой и двумя машинами, красной и чёрной, запрещает:",
 o:["Adelantar a otros vehículos","Circular a más de 50 km/h","Entrar dos coches a la vez"], o_ru:["Обгонять другие машины","Ехать быстрее 50 км/ч","Въезжать двум машинам сразу"], a:0,
 e:"Красная машина — та, которую нельзя обгонять. Запрет до знака отмены."},
{t:"senales", q:"Una señal azul redonda con una bicicleta blanca indica:", q_ru:"Круглый синий знак с белым велосипедом означает:",
 o:["Vía obligatoria para ciclistas","Prohibido el paso a bicicletas","Aparcamiento para bicicletas"], o_ru:["Дорожка, обязательная для велосипедистов","Проезд велосипедам запрещён","Парковка для велосипедов"], a:0,
 e:"Синий круг предписывает: велосипедист обязан ехать именно здесь."},
{t:"senales", q:"La cruz de San Andrés (aspa blanca y roja) anuncia:", q_ru:"Андреевский крест (белый с красным) предупреждает о:",
 o:["Un paso a nivel sin barreras","Un cruce de caminos rurales","El final de la vía asfaltada"], o_ru:["Железнодорожном переезде без шлагбаума","Перекрёстке просёлочных дорог","Конце асфальтовой дороги"], a:0,
 e:"Косой крест всегда про рельсы: дальше переезд, и поезд не остановится."},
{t:"senales", q:"Un panel debajo de la señal de STOP con una distancia indica:", q_ru:"Табличка с расстоянием под знаком STOP означает:",
 o:["A cuántos metros habrá que detenerse","La longitud del tramo sin prioridad","La distancia hasta el siguiente pueblo"], o_ru:["Через сколько метров придётся остановиться","Длину участка без приоритета","Расстояние до следующего посёлка"], a:0,
 e:"Знак предупреждает заранее: сам STOP будет через указанное расстояние."},

// --- приоритет ---
{t:"prioridad", q:"Ante un paso a nivel, la prioridad la tiene siempre:", q_ru:"На железнодорожном переезде приоритет всегда у:",
 o:["El tren, en cualquier circunstancia","El vehículo que llegó primero","El que circula por la carretera"], o_ru:["Поезда, при любых обстоятельствах","Того, кто подъехал первым","Того, кто едет по дороге"], a:0,
 e:"Поезду нужно полкилометра на остановку — уступает всегда машина."},
{t:"prioridad", q:"En una pendiente estrecha donde no caben dos vehículos:", q_ru:"На узком подъёме, где двоим не разъехаться:",
 o:["Tiene prioridad el que sube la pendiente","Tiene prioridad el que baja rodando","Pasa primero el que llegue antes"], o_ru:["Приоритет у того, кто поднимается","Приоритет у того, кто спускается","Первым едет тот, кто раньше подъехал"], a:0,
 e:"Поднимающемуся труднее тронуться с места — поэтому уступает спускающийся."},
{t:"prioridad", q:"Al salir de una glorieta hay que:", q_ru:"При съезде с кругового нужно:",
 o:["Señalizar a la derecha antes de salir","Señalizar a la izquierda al entrar","No señalizar, se ve por la trayectoria"], o_ru:["Показать поворот направо перед съездом","Показать налево при въезде","Не показывать, и так видно по траектории"], a:0,
 e:"Правый поворотник на выходе — единственный сигнал, который понимают остальные."},
{t:"prioridad", q:"Un grupo de ciclistas cuyo primer miembro ya ha entrado en el cruce:", q_ru:"Группа велосипедистов, первый из которой уже въехал на перекрёсток:",
 o:["Tiene prioridad todo el grupo para pasar","Debe partirse y ceder el paso","Pierde la prioridad en ese momento"], o_ru:["Имеет приоритет вся группа целиком","Должна разделиться и уступить","Теряет приоритет в этот момент"], a:0,
 e:"Группу не разрывают: въехал первый — проезжают все."},
{t:"prioridad", q:"Un peatón con bastón blanco cruzando la calzada:", q_ru:"Пешеход с белой тростью, переходящий дорогу:",
 o:["Tiene prioridad absoluta sobre el tráfico","Debe esperar igual que cualquier peatón","Tiene prioridad solo en los pasos de cebra"], o_ru:["Имеет безусловный приоритет","Ждёт наравне с любым другим пешеходом","Имеет приоритет только на самой зебре"], a:0,
 e:"Белая трость означает, что человек не видит машину. Пропускают везде."},
{t:"prioridad", q:"Para salir de una autovía hay que usar:", q_ru:"Чтобы съехать с автомагистрали, нужно использовать:",
 o:["El carril de deceleración, frenando en él","El arcén derecho, frenando antes","El carril central hasta el último metro"], o_ru:["Полосу торможения, тормозя уже на ней","Правую обочину, тормозя заранее","Среднюю полосу до последнего метра"], a:0,
 e:"Тормозить в потоке опасно: скорость сбрасывают, уже уйдя на полосу съезда."},
{t:"prioridad", q:"En un estrechamiento donde tu flecha es la roja:", q_ru:"На сужении, где твоя стрелка красная:",
 o:["Cedes el paso al sentido contrario","Tienes prioridad para pasar primero","Pasa el que llegue antes al tramo"], o_ru:["Уступаешь встречному направлению","У тебя приоритет, проезжаешь первым","Едет тот, кто раньше подъехал"], a:0,
 e:"Красная стрелка — твоя, значит уступаешь ты. Чёрная — приоритет твой."},
{t:"prioridad", q:"Un vehículo que circula marcha atrás por una vía:", q_ru:"Машина, движущаяся задним ходом по дороге:",
 o:["Cede el paso a todos los demás","Mantiene la prioridad que tenía","Tiene prioridad por ser maniobra"], o_ru:["Уступает всем остальным","Сохраняет прежний приоритет","Имеет приоритет, это же манёвр"], a:0,
 e:"Задний ход — манёвр с нуля приоритета, как и разворот."},

// --- алкоголь ---
{t:"alcohol", q:"Un ciclista está sujeto a las tasas de alcohol:", q_ru:"Велосипедист подчиняется нормам алкоголя:",
 o:["Las mismas que cualquier conductor","Ninguna, la bici no es vehículo","Solo la mitad de las del coche"], o_ru:["Тем же, что и любой водитель","Никаким, велосипед не транспорт","Половинным от автомобильных"], a:0,
 e:"Велосипед в Испании — транспортное средство, и проверяют так же."},
{t:"alcohol", q:"El control de drogas al volante se hace habitualmente con:", q_ru:"Проверку на наркотики за рулём обычно делают по:",
 o:["Una muestra de saliva del conductor","Una muestra de sangre en el acto","Un simple examen visual del agente"], o_ru:["Пробе слюны водителя","Пробе крови прямо на месте","Простому осмотру глазами инспектора"], a:0,
 e:"Слюну берут на месте, кровь — только потом и по спору."},
{t:"alcohol", q:"Tras dar positivo en alcohol, el vehículo:", q_ru:"После положительного теста на алкоголь машину:",
 o:["Puede ser inmovilizado en el acto","Sigue el viaje sin más trámite","Se lleva siempre al depósito"], o_ru:["Могут задержать прямо на месте","Отпускают дальше без последствий","Всегда увозят на штрафстоянку"], a:0,
 e:"Машину останавливают до приезда трезвого водителя."},
{t:"alcohol", q:"El conductor de un autobús escolar tiene una tasa de:", q_ru:"У водителя школьного автобуса норма алкоголя:",
 o:["0,15 mg/l, como todo profesional","0,25 mg/l, como cualquiera","0,30 mg/l por la responsabilidad"], o_ru:["0,15 мг/л, как у всех профессионалов","0,25 мг/л, как у всех","0,30 мг/л ввиду ответственности"], a:0,
 e:"Профессиональные водители — половинная норма, без исключений."},
{t:"alcohol", q:"Antes de tomar un medicamento y conducir conviene:", q_ru:"Перед тем как принять лекарство и сесть за руль, стоит:",
 o:["Leer el prospecto y preguntar en farmacia","Fiarse de cómo sienta la primera vez","Tomar la mitad de la dosis indicada"], o_ru:["Прочесть вкладыш и спросить в аптеке","Понадеяться на первое ощущение","Принять половину дозы"], a:0,
 e:"Значок с машиной на упаковке — это и есть ответ, но вкладыш точнее."},
{t:"alcohol", q:"El cansancio al volante, comparado con el alcohol:", q_ru:"Усталость за рулём по сравнению с алкоголем:",
 o:["Alarga la reacción de forma parecida","No influye si se duerme después","Solo afecta de noche, nunca de día"], o_ru:["Так же удлиняет реакцию","Не влияет, если выспаться потом","Влияет только ночью, днём нет"], a:0,
 e:"Восемнадцать часов без сна по реакции сравнимы с нормой алкоголя на грани."},

// --- штрафы и баллы ---
{t:"multas", q:"El importe habitual de una infracción grave es de:", q_ru:"Обычный размер штрафа за серьёзное нарушение:",
 o:["200 euros","100 euros","500 euros"], o_ru:["200 евро","100 евро","500 евро"], a:0,
 e:"Лёгкое — до 100, серьёзное — 200, особо тяжкое — 500 и выше."},
{t:"multas", q:"Llevar el móvil sujeto en un soporte y usarlo por voz:", q_ru:"Телефон в держателе, управляемый голосом:",
 o:["Está permitido si no se manipula","Está prohibido igual que en la mano","Se permite solo fuera de ciudad"], o_ru:["Разрешено, если его не трогать руками","Запрещено так же, как в руке","Разрешено только за городом"], a:0,
 e:"Наказывают не телефон, а руку на нём: шесть баллов стоит именно держать."},
{t:"multas", q:"No señalizar con el intermitente un cambio de carril:", q_ru:"Смена полосы без поворотника:",
 o:["Es una infracción sancionable","No se sanciona si no hay nadie","Solo se sanciona en autopista"], o_ru:["Наказуемое нарушение","Не наказывается, если никого нет","Наказывается только на магистрали"], a:0,
 e:"Поворотник — обязанность, а не вежливость."},
{t:"multas", q:"Entrar en una Zona de Bajas Emisiones sin distintivo:", q_ru:"Въезд в зону низких выбросов (ZBE) без экологической наклейки:",
 o:["Se sanciona con multa por cámara","Se permite si es un viaje corto","Solo se sanciona a los camiones"], o_ru:["Штрафуют по камере","Можно, если поездка короткая","Штрафуют только грузовики"], a:0,
 e:"Зоны обязательны в городах больше 50 тысяч жителей, а въезд читают камеры."},
{t:"multas", q:"El curso de recuperación parcial de puntos:", q_ru:"Курс частичного восстановления баллов:",
 o:["Devuelve 6 puntos y dura 12 horas","Devuelve todos los puntos perdidos","Se puede hacer cada seis meses"], o_ru:["Возвращает 6 баллов, длится 12 часов","Возвращает все потерянные баллы","Проходится каждые полгода"], a:0,
 e:"Шесть баллов за двенадцать часов, и не чаще раза в два года."},
{t:"multas", q:"Las infracciones muy graves prescriben a los:", q_ru:"Срок давности по особо тяжким нарушениям:",
 o:["Seis meses desde la infracción","Veinte días desde la multa","Dos años desde la infracción"], o_ru:["Шесть месяцев с момента нарушения","Двадцать дней с момента штрафа","Два года с момента нарушения"], a:0,
 e:"Лёгкие сгорают за три месяца, серьёзные и тяжкие — за шесть."},
{t:"multas", q:"Estacionar en una plaza reservada para personas con discapacidad:", q_ru:"Парковка на месте для людей с инвалидностью:",
 o:["Es infracción grave con multa alta","Se permite si es por poco tiempo","Se permite si no hay otras plazas"], o_ru:["Серьёзное нарушение с крупным штрафом","Можно, если ненадолго","Можно, если других мест нет"], a:0,
 e:"Эвакуатор приезжает быстрее, чем человек успевает вернуться."},
{t:"multas", q:"Si el titular del vehículo no identifica al conductor infractor:", q_ru:"Если владелец машины не назовёт нарушившего водителя:",
 o:["Se le sanciona a él con multa mayor","No ocurre nada, la multa se anula","La multa pasa al seguro del coche"], o_ru:["Штрафуют его самого, и крупнее","Ничего, штраф аннулируется","Штраф уходит в страховую"], a:0,
 e:"Молчание владельца стоит дороже самого нарушения."},

// --- безопасность ---
{t:"seguridad", q:"Las cadenas o neumáticos de invierno son obligatorios:", q_ru:"Цепи или зимние шины обязательны:",
 o:["Cuando lo indique la señalización","Todo el invierno en cualquier vía","Solo por encima de mil metros"], o_ru:["Когда это предписано знаком","Всю зиму на любой дороге","Только выше тысячи метров"], a:0,
 e:"В Испании нет общего зимнего правила: решает знак на въезде в участок."},
{t:"seguridad", q:"Llevar extintor en un turismo particular:", q_ru:"Огнетушитель в личном легковом автомобиле:",
 o:["No es obligatorio, aunque es útil","Es obligatorio desde el año 2024","Es obligatorio solo en verano"], o_ru:["Необязателен, хотя полезен","Обязателен с 2024 года","Обязателен только летом"], a:0,
 e:"Обязателен он у грузовиков и автобусов, а не у легковых."},
{t:"seguridad", q:"Los chalecos reflectantes que hay que llevar son:", q_ru:"Светоотражающих жилетов нужно возить:",
 o:["Uno por cada ocupante que vaya a salir","Uno solo, para el conductor","Ninguno desde la llegada del V-16"], o_ru:["По одному на каждого, кто выйдет","Один, для водителя","Ни одного, раз появился V-16"], a:0,
 e:"Маячок V-16 обозначает машину, а жилет — человека. Одно другое не заменяет."},
{t:"seguridad", q:"Un bebé de menos de 15 meses debe viajar:", q_ru:"Ребёнок младше 15 месяцев должен ехать:",
 o:["En sentido contrario a la marcha","Mirando hacia delante desde el año","En el asiento delantero con airbag"], o_ru:["Против хода движения","Лицом вперёд начиная с года","На переднем сиденье с подушкой"], a:0,
 e:"Против хода — шея младенца не держит удар при лобовом."},
{t:"seguridad", q:"Si se coloca una silla contramarcha en el asiento delantero:", q_ru:"Если кресло против хода ставят на переднее сиденье:",
 o:["Hay que desactivar el airbag frontal","Basta con retrasar el asiento del todo","No se puede hacer en ningún caso"], o_ru:["Нужно отключить фронтальную подушку","Достаточно отодвинуть сиденье назад","Нельзя делать ни при каких условиях"], a:0,
 e:"Раскрывшаяся подушка бьёт по спинке кресла, то есть по голове ребёнка."},
{t:"seguridad", q:"Una carga que sobresale por detrás se señaliza con:", q_ru:"Груз, выступающий сзади, обозначают:",
 o:["El panel V-20, rojo y blanco a rayas","Un trapo rojo atado al extremo","Las luces de emergencia encendidas"], o_ru:["Щитком V-20 в красно-белую полоску","Красной тряпкой на конце","Включённой аварийкой"], a:0,
 e:"Тряпка не считается: нужен именно светоотражающий щиток."},
{t:"seguridad", q:"El uso del claxon en ciudad está permitido:", q_ru:"Сигналить в городе разрешено:",
 o:["Solo para evitar un peligro inminente","Para avisar de que vas a adelantar","Para saludar o meter prisa a otro"], o_ru:["Только чтобы предотвратить опасность","Чтобы предупредить об обгоне","Чтобы поздороваться или поторопить"], a:0,
 e:"В городе гудок — сигнал тревоги, а не средство общения."},
{t:"seguridad", q:"Las luces de emergencia se usan, entre otros casos, para:", q_ru:"Аварийку включают, среди прочего, чтобы:",
 o:["Avisar de una retención repentina","Aparcar en doble fila un momento","Circular con niebla muy densa"], o_ru:["Предупредить о внезапной пробке","Постоять вторым рядом минутку","Ехать в очень густом тумане"], a:0,
 e:"Вторым рядом аварийка стоять не разрешает — это частое заблуждение."},

// --- документы ---
{t:"documentos", q:"El distintivo ambiental de la DGT clasifica los coches en:", q_ru:"Экологическая наклейка DGT делит машины на категории:",
 o:["0, ECO, C y B según emisiones","A, B, C y D según antigüedad","1, 2 y 3 según el combustible"], o_ru:["0, ECO, C и B по выбросам","A, B, C и D по возрасту","1, 2 и 3 по топливу"], a:0,
 e:"Самые старые машины наклейки не получают вовсе — и в зоны ZBE не въезжают."},
{t:"documentos", q:"Las Zonas de Bajas Emisiones son obligatorias en ciudades de más de:", q_ru:"Зоны низких выбросов обязательны в городах с населением больше:",
 o:["50.000 habitantes","20.000 habitantes","100.000 habitantes"], o_ru:["50 тысяч жителей","20 тысяч жителей","100 тысяч жителей"], a:0,
 e:"Порог низкий, так что зона есть почти в каждом городе, куда человек переезжает."},
{t:"documentos", q:"El permiso AM, para ciclomotores, se obtiene a partir de los:", q_ru:"Категорию AM (мопеды) можно получить с:",
 o:["15 años","16 años","14 años"], o_ru:["15 лет","16 лет","14 лет"], a:0,
 e:"Пятнадцать — мопед, шестнадцать — лёгкий мотоцикл A1."},
{t:"documentos", q:"El permiso A1 permite conducir motos de hasta:", q_ru:"Категория A1 разрешает мотоциклы объёмом до:",
 o:["125 cc, desde los 16 años","250 cc, desde los 18 años","50 cc, desde los 15 años"], o_ru:["125 кубиков, с 16 лет","250 кубиков, с 18 лет","50 кубиков, с 15 лет"], a:0,
 e:"Сто двадцать пять кубиков — самая ходовая городская мотокатегория."},
{t:"documentos", q:"Con el permiso B se puede arrastrar un remolque de hasta:", q_ru:"С категорией B можно тянуть прицеп массой до:",
 o:["750 kg sin permiso adicional","1.500 kg sin permiso adicional","350 kg sin permiso adicional"], o_ru:["750 кг без дополнительных прав","1500 кг без дополнительных прав","350 кг без дополнительных прав"], a:0,
 e:"Тяжелее — нужна отметка B96 или отдельная категория BE."},
{t:"documentos", q:"El seguro obligatorio del vehículo cubre:", q_ru:"Обязательная страховка автомобиля покрывает:",
 o:["Los daños causados a terceros","Todos los daños del propio coche","Solo los daños del conductor"], o_ru:["Ущерб, причинённый другим","Любой ущерб собственной машине","Только ущерб самого водителя"], a:0,
 e:"Своя машина — это уже добровольное страхование, за отдельные деньги."},
{t:"documentos", q:"Circular con la ITV caducada supone:", q_ru:"Езда с просроченным техосмотром (ITV) означает:",
 o:["Multa, y el seguro puede complicarse","Solo un aviso hasta pasar la ITV","Nada mientras el coche funcione"], o_ru:["Штраф, и со страховкой будут сложности","Только предупреждение до техосмотра","Ничего, пока машина на ходу"], a:0,
 e:"При аварии просроченный ITV страховая вспомнит первым делом."},
{t:"documentos", q:"El permiso internacional de conducción sirve para:", q_ru:"Международное водительское удостоверение нужно, чтобы:",
 o:["Acompañar al permiso en ciertos países","Sustituir al permiso español fuera","Conducir sin examen en toda Europa"], o_ru:["Дополнять национальные права в ряде стран","Заменять испанские права за границей","Ездить по Европе без экзамена"], a:0,
 e:"Это перевод, а не право: без основных прав он ничего не значит."},
];
if (typeof module !== "undefined") module.exports = PREGUNTAS;
